// ============================================================
//  CptMarkets — lang.js
//  সম্পূর্ণ ওয়েবসাইটের জন্য ১০টি ভাষা
//  10 International Languages for all pages
// ============================================================

const languageData = {

  // ─────────────────────────────────────────
  // 1. English (UK) 🇬🇧
  // ─────────────────────────────────────────
  en_UK: {
    flag: "🇬🇧",
    langName: "English (UK)",

    // LOGIN
    username: "Username",
    password: "Password",
    signin: "Go to Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",

    // REGISTER
    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",

    // NAVIGATION (Bottom bar)
    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Mine",
    navTrade: "Trade",

    // DASHBOARD
    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",

    // MARKETS
    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",

    // ASSETS
    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",

    // TRADE
    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",

    // MINE (Profile)
    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",

    // DEPOSIT
    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",

    // WITHDRAW
    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",

    // TRANSFER
    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",

    // INVITE
    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",

    // SUPPORT
    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",

    // INVESTMENT / WEALTH
    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",

    // COPY TRADE
    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",

    // SETTINGS
    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",

    // LOAN
    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",

    // ORDERS
    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",

    // COMMON
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },

  // ─────────────────────────────────────────
  // 2. বাংলা 🇧🇩
  // ─────────────────────────────────────────
  bn_BD: {
    flag: "🇧🇩",
    langName: "বাংলা",

    username: "ইউজারনেম",
    password: "পাসওয়ার্ড",
    signin: "লগইন করুন",
    createAccount: "অ্যাকাউন্ট খুলুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",

    regTitle: "অ্যাকাউন্ট তৈরি করুন",
    regSubtitle: "বৈশ্বিক ট্রেডিংয়ের জন্য CptMarkets-এ যোগ দিন",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    inviteCode: "আমন্ত্রণ কোড (ঐচ্ছিক)",
    register: "নিবন্ধন করুন",
    alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    signIn: "সাইন ইন",

    navHome: "হোম",
    navMarkets: "মার্কেট",
    navAssets: "সম্পদ",
    navMine: "প্রোফাইল",
    navTrade: "ট্রেড",

    totalAssets: "মোট সম্পদ (USD)",
    floatingPL: "ভাসমান লাভ/লোকসান",
    equity: "ইকুইটি",
    deposit: "জমা",
    withdraw: "উত্তোলন",
    transfer: "ট্রান্সফার",
    support: "সাপোর্ট",
    copyTrade: "কপি ট্রেড",
    loan: "ঋণ",
    wealth: "ওয়েলথ",
    mining: "মাইনিং",
    invite: "আমন্ত্রণ",
    hotMarkets: "হট মার্কেট",
    viewAll: "সব দেখুন",

    all: "সব",
    forex: "ফরেক্স",
    crypto: "ক্রিপ্টো",
    metals: "ধাতু",
    indices: "সূচক",
    notifications: "বিজ্ঞপ্তি",
    close: "বন্ধ করুন",

    assetsTitle: "সম্পদ",
    available: "উপলব্ধ",
    frozen: "জমাট",
    fundingAccount: "ফান্ডিং অ্যাকাউন্ট",
    mainWalletBalance: "মূল ওয়ালেট ব্যালেন্স",
    spotAccount: "স্পট অ্যাকাউন্ট",
    spotTradingAssets: "স্পট ট্রেডিং সম্পদ",
    futuresAccount: "ফিউচার্স অ্যাকাউন্ট",
    futuresBalance: "ফিউচার্স ব্যালেন্স",
    myAssets: "আমার সম্পদ",
    history: "ইতিহাস",
    noRecords: "কোনো রেকর্ড নেই",

    leverage: "লিভারেজ",
    convertedLots: "রূপান্তরিত লট",
    contractValue: "চুক্তির মূল্য",
    entryPrice: "প্রবেশ মূল্য",
    currentPrice: "বর্তমান মূল্য",
    amount: "পরিমাণ",
    buyUp: "কিনুন (আপ)",
    sellDown: "বিক্রি করুন (ডাউন)",
    openOrders: "খোলা অর্ডার",
    orderHistory: "অর্ডার ইতিহাস",

    todayPL: "আজকের লাভ/লোকসান",
    totalPL: "মোট লাভ/লোকসান",
    open: "খোলা",
    myOrders: "আমার অর্ডার",
    copyTrading: "কপি ট্রেডিং",
    wealthMining: "ওয়েলথ / মাইনিং",
    inviteFriends: "বন্ধু আমন্ত্রণ",
    walletManagement: "ওয়ালেট ম্যানেজমেন্ট",
    security: "নিরাপত্তা",
    announcements: "ঘোষণা",
    signOut: "সাইন আউট",
    loginPassword: "লগইন পাসওয়ার্ড",
    protectAccount: "একটি শক্তিশালী পাসওয়ার্ড দিয়ে অ্যাকাউন্ট সুরক্ষিত রাখুন।",
    accountSecurity: "অ্যাকাউন্ট নিরাপত্তা",
    keepAccountSafe: "আপনার অ্যাকাউন্টের তথ্য সুরক্ষিত রাখুন।",
    securityVerification: "নিরাপত্তা যাচাইকরণ",
    manageVerification: "আপনার অ্যাকাউন্ট যাচাইকরণ সেটিংস পরিচালনা করুন।",

    depositTitle: "জমা",
    fundAccount: "আপনার CptMarkets অ্যাকাউন্টে অর্থ যোগ করুন",
    depositGuidelines: "জমার নির্দেশিকা",
    startRequest: "অনুরোধ শুরু করুন",
    provideUID: "আপনার অ্যাকাউন্ট UID দিন",
    confirmPayment: "পেমেন্টের বিবরণ নিশ্চিত করুন",
    submitReceipt: "আপনার রসিদ জমা দিন",
    officialSupport: "অফিসিয়াল সাপোর্ট চ্যানেল ব্যবহার করুন",
    onlineCustomerService: "অনলাইন গ্রাহক সেবা",
    depositAssistance: "জমার সহায়তা",
    depositInfo: "জমার তথ্য",

    globalWithdrawal: "গ্লোবাল ফান্ড উত্তোলন",
    availableUSDT: "উপলব্ধ USDT ব্যালেন্স",
    paymentMethod: "আন্তর্জাতিক পেমেন্ট পদ্ধতি",
    selectPayout: "পেআউট সিস্টেম নির্বাচন করুন",
    enterAmount: "আপনার পরিমাণ লিখুন",
    confirmWithdrawal: "উত্তোলন নিশ্চিত করুন",
    payoutGateway: "পেআউট গেটওয়ে নির্বাচন করুন",
    bankWire: "আন্তর্জাতিক ব্যাংক ওয়্যার ট্রান্সফার",
    cryptoWallet: "ক্রিপ্টো নেটওয়ার্ক ওয়ালেট",
    enterMobile: "মোবাইল নম্বর / ওয়ালেট আইডি লিখুন",
    cryptoAddress: "আপনার নেটওয়ার্ক ওয়ালেট ঠিকানা পেস্ট করুন",
    securityPassword: "নিরাপত্তা পাসওয়ার্ড লিখুন",

    transferTitle: "ট্রান্সফার",
    transferFunds: "তহবিল স্থানান্তর",
    fromAccount: "উৎস অ্যাকাউন্ট",
    toAccount: "গন্তব্য অ্যাকাউন্ট",
    transferAmount: "স্থানান্তর পরিমাণ",
    confirm: "নিশ্চিত করুন",

    inviteTitle: "বন্ধু আমন্ত্রণ",
    myReferrals: "আমার রেফারেল",
    copyLink: "আমন্ত্রণ লিংক কপি করুন",
    shareCode: "কোড শেয়ার করুন",
    totalReferrals: "মোট রেফারেল",

    accountHelp: "অ্যাকাউন্ট সহায়তা",
    manageProfile: "প্রোফাইল পরিচালনা",
    addFunds: "নিরাপদে অর্থ যোগ করুন",
    payoutRequests: "পেআউট অনুরোধ",
    generalSupport: "সাধারণ সাপোর্ট",

    wealthTitle: "ওয়েলথ",
    noSubscriptions: "কোনো সাবস্ক্রিপশন নেই",
    dailyIncome: "দৈনিক আয়",
    duration: "মেয়াদ",
    minimum: "সর্বনিম্ন",
    subscribe: "সাবস্ক্রাইব",
    days: "দিন",

    copySquare: "কপি স্কোয়ার",
    professional: "প্রফেশনাল",
    amateur: "অ্যামেচার",
    myMaster: "আমার মাস্টার",
    profitRate: "মুনাফার হার",

    settingsTitle: "সেটিংস",
    changePassword: "পাসওয়ার্ড ও নিরাপত্তা পরিবর্তন",
    language: "ভাষা",
    darkMode: "ডার্ক মোড",
    appVersion: "অ্যাপ ভার্সন",
    latest: "সর্বশেষ",

    loanTitle: "ঋণ",
    applyLoan: "ঋণের জন্য আবেদন",
    loanAmount: "ঋণের পরিমাণ",
    repayment: "পরিশোধ",
    interestRate: "সুদের হার",

    ordersTitle: "আমার অর্ডার",
    noOrders: "কোনো অর্ডার পাওয়া যায়নি",
    profit: "লাভ",
    loss: "লোকসান",
    status: "অবস্থা",
    symbol: "সিম্বল",
    orderType: "অর্ডারের ধরন",

    loading: "লোড হচ্ছে...",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    submit: "জমা দিন",
    ok: "ঠিক আছে",
    back: "পিছনে",
    next: "পরবর্তী",
    globalPlatform: "গ্লোবাল ইন্টিগ্রেটেড ফিনান্সিয়াল ট্রেডিং প্ল্যাটফর্ম",
  },

  // ─────────────────────────────────────────
  // 3. हिन्दी 🇮🇳
  // ─────────────────────────────────────────
  hi_IN: {
    flag: "🇮🇳",
    langName: "हिन्दी",

    username: "यूजरनेम",
    password: "पासवर्ड",
    signin: "साइन इन करें",
    createAccount: "खाता बनाएं",
    forgotPassword: "पासवर्ड भूल गए?",

    regTitle: "खाता बनाएं",
    regSubtitle: "वैश्विक ट्रेडिंग के लिए CptMarkets से जुड़ें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    inviteCode: "आमंत्रण कोड (वैकल्पिक)",
    register: "पंजीकरण करें",
    alreadyAccount: "पहले से खाता है?",
    signIn: "साइन इन",

    navHome: "होम",
    navMarkets: "बाज़ार",
    navAssets: "संपत्ति",
    navMine: "प्रोफ़ाइल",
    navTrade: "ट्रेड",

    totalAssets: "कुल संपत्ति (USD)",
    floatingPL: "फ्लोटिंग लाभ/हानि",
    equity: "इक्विटी",
    deposit: "जमा",
    withdraw: "निकासी",
    transfer: "ट्रांसफर",
    support: "सहायता",
    copyTrade: "कॉपी ट्रेड",
    loan: "ऋण",
    wealth: "वेल्थ",
    mining: "माइनिंग",
    invite: "आमंत्रित करें",
    hotMarkets: "हॉट मार्केट",
    viewAll: "सब देखें",

    all: "सभी",
    forex: "फॉरेक्स",
    crypto: "क्रिप्टो",
    metals: "धातु",
    indices: "सूचकांक",
    notifications: "सूचनाएं",
    close: "बंद करें",

    assetsTitle: "संपत्ति",
    available: "उपलब्ध",
    frozen: "फ्रोज़न",
    fundingAccount: "फंडिंग खाता",
    mainWalletBalance: "मुख्य वॉलेट बैलेंस",
    spotAccount: "स्पॉट खाता",
    spotTradingAssets: "स्पॉट ट्रेडिंग संपत्ति",
    futuresAccount: "फ्यूचर्स खाता",
    futuresBalance: "फ्यूचर्स बैलेंस",
    myAssets: "मेरी संपत्ति",
    history: "इतिहास",
    noRecords: "कोई रिकॉर्ड नहीं",

    leverage: "लीवरेज",
    convertedLots: "परिवर्तित लॉट",
    contractValue: "अनुबंध मूल्य",
    entryPrice: "प्रवेश मूल्य",
    currentPrice: "वर्तमान मूल्य",
    amount: "राशि",
    buyUp: "खरीदें (अप)",
    sellDown: "बेचें (डाउन)",
    openOrders: "खुले ऑर्डर",
    orderHistory: "ऑर्डर इतिहास",

    todayPL: "आज का लाभ/हानि",
    totalPL: "कुल लाभ/हानि",
    open: "खुला",
    myOrders: "मेरे ऑर्डर",
    copyTrading: "कॉपी ट्रेडिंग",
    wealthMining: "वेल्थ / माइनिंग",
    inviteFriends: "दोस्तों को आमंत्रित करें",
    walletManagement: "वॉलेट प्रबंधन",
    security: "सुरक्षा",
    announcements: "घोषणाएं",
    signOut: "साइन आउट",
    loginPassword: "लॉगिन पासवर्ड",
    protectAccount: "एक सुरक्षित पासवर्ड से अपना खाता सुरक्षित रखें।",
    accountSecurity: "खाता सुरक्षा",
    keepAccountSafe: "अपनी खाता जानकारी सुरक्षित रखें।",
    securityVerification: "सुरक्षा सत्यापन",
    manageVerification: "अपने खाता सत्यापन सेटिंग्स प्रबंधित करें।",

    depositTitle: "जमा",
    fundAccount: "अपने CptMarkets खाते में फंड करें",
    depositGuidelines: "जमा दिशानिर्देश",
    startRequest: "अनुरोध शुरू करें",
    provideUID: "अपना खाता UID दें",
    confirmPayment: "भुगतान विवरण की पुष्टि करें",
    submitReceipt: "अपनी रसीद जमा करें",
    officialSupport: "आधिकारिक सहायता चैनल का उपयोग करें",
    onlineCustomerService: "ऑनलाइन ग्राहक सेवा",
    depositAssistance: "जमा सहायता",
    depositInfo: "जमा जानकारी",

    globalWithdrawal: "वैश्विक फंड निकासी",
    availableUSDT: "उपलब्ध USDT बैलेंस",
    paymentMethod: "अंतर्राष्ट्रीय भुगतान विधि",
    selectPayout: "पेआउट सिस्टम चुनें",
    enterAmount: "अपनी राशि दर्ज करें",
    confirmWithdrawal: "निकासी की पुष्टि करें",
    payoutGateway: "पेआउट गेटवे चुनें",
    bankWire: "अंतर्राष्ट्रीय बैंक वायर ट्रांसफर",
    cryptoWallet: "क्रिप्टो नेटवर्क वॉलेट",
    enterMobile: "मोबाइल नंबर / वॉलेट आईडी दर्ज करें",
    cryptoAddress: "अपना नेटवर्क वॉलेट पता पेस्ट करें",
    securityPassword: "सुरक्षा पासवर्ड दर्ज करें",

    transferTitle: "ट्रांसफर",
    transferFunds: "फंड ट्रांसफर",
    fromAccount: "स्रोत खाता",
    toAccount: "गंतव्य खाता",
    transferAmount: "ट्रांसफर राशि",
    confirm: "पुष्टि करें",

    inviteTitle: "दोस्तों को आमंत्रित करें",
    myReferrals: "मेरे रेफरल",
    copyLink: "आमंत्रण लिंक कॉपी करें",
    shareCode: "कोड शेयर करें",
    totalReferrals: "कुल रेफरल",

    accountHelp: "खाता सहायता",
    manageProfile: "प्रोफ़ाइल प्रबंधित करें",
    addFunds: "सुरक्षित रूप से फंड जोड़ें",
    payoutRequests: "पेआउट अनुरोध",
    generalSupport: "सामान्य सहायता",

    wealthTitle: "वेल्थ",
    noSubscriptions: "कोई सदस्यता नहीं",
    dailyIncome: "दैनिक आय",
    duration: "अवधि",
    minimum: "न्यूनतम",
    subscribe: "सदस्यता लें",
    days: "दिन",

    copySquare: "कॉपी स्क्वायर",
    professional: "प्रोफेशनल",
    amateur: "शौकिया",
    myMaster: "मेरा मास्टर",
    profitRate: "लाभ दर",

    settingsTitle: "सेटिंग्स",
    changePassword: "पासवर्ड और सुरक्षा विकल्प बदलें",
    language: "भाषा",
    darkMode: "डार्क मोड",
    appVersion: "ऐप वर्जन",
    latest: "नवीनतम",

    loanTitle: "ऋण",
    applyLoan: "ऋण के लिए आवेदन करें",
    loanAmount: "ऋण राशि",
    repayment: "पुनर्भुगतान",
    interestRate: "ब्याज दर",

    ordersTitle: "मेरे ऑर्डर",
    noOrders: "कोई ऑर्डर नहीं मिला",
    profit: "लाभ",
    loss: "हानि",
    status: "स्थिति",
    symbol: "सिम्बल",
    orderType: "ऑर्डर प्रकार",

    loading: "लोड हो रहा है...",
    save: "सहेजें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    ok: "ठीक है",
    back: "वापस",
    next: "अगला",
    globalPlatform: "वैश्विक एकीकृत वित्तीय ट्रेडिंग प्लेटफॉर्म",
  },

  // ─────────────────────────────────────────
  // 4. English (US) 🇺🇸
  // ─────────────────────────────────────────
  en_US: {
    flag: "🇺🇸",
    langName: "English (US)",
    username: "Username",
    password: "Password",
    signin: "Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",
    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",
    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Profile",
    navTrade: "Trade",
    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",
    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",
    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",
    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",
    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",
    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",
    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",
    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",
    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",
    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",
    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",
    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",
    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",
    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",
    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },

  // ─────────────────────────────────────────
  // 5. Español 🇪🇸
  // ─────────────────────────────────────────
  es_ES: {
    flag: "🇪🇸",
    langName: "Español",
    username: "Usuario",
    password: "Contraseña",
    signin: "Iniciar sesión",
    createAccount: "Crear cuenta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    regTitle: "Crear cuenta",
    regSubtitle: "Únete a CptMarkets para trading global",
    confirmPassword: "Confirmar contraseña",
    inviteCode: "Código de invitación (opcional)",
    register: "Registrarse",
    alreadyAccount: "¿Ya tienes una cuenta?",
    signIn: "Iniciar sesión",
    navHome: "Inicio",
    navMarkets: "Mercados",
    navAssets: "Activos",
    navMine: "Perfil",
    navTrade: "Trading",
    totalAssets: "Activos Totales (USD)",
    floatingPL: "P/G Flotante",
    equity: "Patrimonio",
    deposit: "Depositar",
    withdraw: "Retirar",
    transfer: "Transferir",
    support: "Soporte",
    copyTrade: "Copiar Trade",
    loan: "Préstamo",
    wealth: "Riqueza",
    mining: "Minería",
    invite: "Invitar",
    hotMarkets: "Mercados Destacados",
    viewAll: "Ver Todo",
    all: "Todo",
    forex: "Forex",
    crypto: "Cripto",
    metals: "Metales",
    indices: "Índices",
    notifications: "Notificaciones",
    close: "Cerrar",
    assetsTitle: "Activos",
    available: "Disponible",
    frozen: "Congelado",
    fundingAccount: "Cuenta de Fondos",
    mainWalletBalance: "Saldo Principal de Cartera",
    spotAccount: "Cuenta Spot",
    spotTradingAssets: "Activos Spot",
    futuresAccount: "Cuenta Futuros",
    futuresBalance: "Saldo Futuros",
    myAssets: "Mis Activos",
    history: "Historial",
    noRecords: "Sin registros",
    leverage: "Apalancamiento",
    convertedLots: "Lotes Convertidos",
    contractValue: "Valor del Contrato",
    entryPrice: "Precio de Entrada",
    currentPrice: "Precio Actual",
    amount: "Cantidad",
    buyUp: "Comprar (Subida)",
    sellDown: "Vender (Bajada)",
    openOrders: "Órdenes Abiertas",
    orderHistory: "Historial de Órdenes",
    todayPL: "P/G Hoy",
    totalPL: "P/G Total",
    open: "Abierto",
    myOrders: "Mis Órdenes",
    copyTrading: "Copiar Trading",
    wealthMining: "Riqueza / Minería",
    inviteFriends: "Invitar Amigos",
    walletManagement: "Gestión de Cartera",
    security: "Seguridad",
    announcements: "Anuncios",
    signOut: "Cerrar Sesión",
    loginPassword: "Contraseña de Acceso",
    protectAccount: "Protege tu cuenta con una contraseña segura.",
    accountSecurity: "Seguridad de Cuenta",
    keepAccountSafe: "Mantén segura tu información de cuenta.",
    securityVerification: "Verificación de Seguridad",
    manageVerification: "Gestiona tu verificación de cuenta.",
    depositTitle: "Depósito",
    fundAccount: "Fondea tu Cuenta CptMarkets",
    depositGuidelines: "Instrucciones de Depósito",
    startRequest: "Iniciar Solicitud",
    provideUID: "Proporciona tu UID de Cuenta",
    confirmPayment: "Confirmar Detalles de Pago",
    submitReceipt: "Enviar Recibo",
    officialSupport: "Usa el Canal de Soporte Oficial",
    onlineCustomerService: "Servicio al Cliente en Línea",
    depositAssistance: "Asistencia de Depósito",
    depositInfo: "Información de Depósito",
    globalWithdrawal: "Retiro Global de Fondos",
    availableUSDT: "Saldo USDT Disponible",
    paymentMethod: "Método de Pago Internacional",
    selectPayout: "Seleccionar sistema de pago",
    enterAmount: "Ingresa tu monto",
    confirmWithdrawal: "Confirmar Retiro",
    payoutGateway: "Seleccionar Pasarela de Pago",
    bankWire: "Transferencia Bancaria Internacional",
    cryptoWallet: "Cartera de Red Cripto",
    enterMobile: "Ingresar Número Móvil / ID de Cartera",
    cryptoAddress: "Pegar dirección de cartera de red",
    securityPassword: "Ingresar contraseña de seguridad",
    transferTitle: "Transferencia",
    transferFunds: "Transferir Fondos",
    fromAccount: "Cuenta Origen",
    toAccount: "Cuenta Destino",
    transferAmount: "Monto a Transferir",
    confirm: "Confirmar",
    inviteTitle: "Invitar Amigos",
    myReferrals: "Mis Referidos",
    copyLink: "Copiar Enlace de Invitación",
    shareCode: "Compartir Código",
    totalReferrals: "Total Referidos",
    accountHelp: "Ayuda de Cuenta",
    manageProfile: "Gestionar perfil",
    addFunds: "Agregar fondos de forma segura",
    payoutRequests: "Solicitudes de pago",
    generalSupport: "Soporte General",
    wealthTitle: "Riqueza",
    noSubscriptions: "Sin suscripciones",
    dailyIncome: "Ingresos Diarios",
    duration: "Duración",
    minimum: "Mínimo",
    subscribe: "Suscribirse",
    days: "Días",
    copySquare: "Plaza de Copia",
    professional: "Profesional",
    amateur: "Aficionado",
    myMaster: "Mi Maestro",
    profitRate: "Tasa de Ganancia",
    settingsTitle: "Configuración",
    changePassword: "Cambiar contraseña y opciones de seguridad",
    language: "Idioma",
    darkMode: "Modo Oscuro",
    appVersion: "Versión de la App",
    latest: "Última",
    loanTitle: "Préstamo",
    applyLoan: "Solicitar Préstamo",
    loanAmount: "Monto del Préstamo",
    repayment: "Reembolso",
    interestRate: "Tasa de Interés",
    ordersTitle: "Mis Órdenes",
    noOrders: "No se encontraron órdenes",
    profit: "Ganancia",
    loss: "Pérdida",
    status: "Estado",
    symbol: "Símbolo",
    orderType: "Tipo de Orden",
    loading: "Cargando...",
    save: "Guardar",
    cancel: "Cancelar",
    submit: "Enviar",
    ok: "Aceptar",
    back: "Atrás",
    next: "Siguiente",
    globalPlatform: "Plataforma financiera global de trading integrado",
  },

  // ─────────────────────────────────────────
  // 6. Français 🇫🇷
  // ─────────────────────────────────────────
  fr_FR: {
    flag: "🇫🇷",
    langName: "Français",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    signin: "Se connecter",
    createAccount: "Créer un compte",
    forgotPassword: "Mot de passe oublié?",
    regTitle: "Créer un compte",
    regSubtitle: "Rejoignez CptMarkets pour le trading mondial",
    confirmPassword: "Confirmer le mot de passe",
    inviteCode: "Code d'invitation (facultatif)",
    register: "S'inscrire",
    alreadyAccount: "Vous avez déjà un compte?",
    signIn: "Se connecter",
    navHome: "Accueil",
    navMarkets: "Marchés",
    navAssets: "Actifs",
    navMine: "Profil",
    navTrade: "Trading",
    totalAssets: "Actifs Totaux (USD)",
    floatingPL: "G/P Flottant",
    equity: "Fonds Propres",
    deposit: "Dépôt",
    withdraw: "Retrait",
    transfer: "Transfert",
    support: "Assistance",
    copyTrade: "Copier le Trade",
    loan: "Prêt",
    wealth: "Richesse",
    mining: "Minage",
    invite: "Inviter",
    hotMarkets: "Marchés Populaires",
    viewAll: "Voir Tout",
    all: "Tout",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Métaux",
    indices: "Indices",
    notifications: "Notifications",
    close: "Fermer",
    assetsTitle: "Actifs",
    available: "Disponible",
    frozen: "Gelé",
    fundingAccount: "Compte de Financement",
    mainWalletBalance: "Solde Principal du Portefeuille",
    spotAccount: "Compte Spot",
    spotTradingAssets: "Actifs de Trading Spot",
    futuresAccount: "Compte Futures",
    futuresBalance: "Solde Futures",
    myAssets: "Mes Actifs",
    history: "Historique",
    noRecords: "Aucun enregistrement",
    leverage: "Effet de Levier",
    convertedLots: "Lots Convertis",
    contractValue: "Valeur du Contrat",
    entryPrice: "Prix d'Entrée",
    currentPrice: "Prix Actuel",
    amount: "Montant",
    buyUp: "Acheter (Hausse)",
    sellDown: "Vendre (Baisse)",
    openOrders: "Ordres Ouverts",
    orderHistory: "Historique des Ordres",
    todayPL: "G/P du Jour",
    totalPL: "G/P Total",
    open: "Ouvert",
    myOrders: "Mes Ordres",
    copyTrading: "Copier le Trading",
    wealthMining: "Richesse / Minage",
    inviteFriends: "Inviter des Amis",
    walletManagement: "Gestion du Portefeuille",
    security: "Sécurité",
    announcements: "Annonces",
    signOut: "Se Déconnecter",
    loginPassword: "Mot de Passe de Connexion",
    protectAccount: "Protégez votre compte avec un mot de passe sécurisé.",
    accountSecurity: "Sécurité du Compte",
    keepAccountSafe: "Gardez vos informations de compte en sécurité.",
    securityVerification: "Vérification de Sécurité",
    manageVerification: "Gérez vos paramètres de vérification de compte.",
    depositTitle: "Dépôt",
    fundAccount: "Alimentez votre Compte CptMarkets",
    depositGuidelines: "Instructions de Dépôt",
    startRequest: "Démarrer la Demande",
    provideUID: "Fournissez votre UID de Compte",
    confirmPayment: "Confirmer les Détails du Paiement",
    submitReceipt: "Soumettre le Reçu",
    officialSupport: "Utiliser le Canal de Support Officiel",
    onlineCustomerService: "Service Client en Ligne",
    depositAssistance: "Assistance au Dépôt",
    depositInfo: "Informations de Dépôt",
    globalWithdrawal: "Retrait Mondial de Fonds",
    availableUSDT: "Solde USDT Disponible",
    paymentMethod: "Méthode de Paiement Internationale",
    selectPayout: "Sélectionner le système de paiement",
    enterAmount: "Entrez votre montant",
    confirmWithdrawal: "Confirmer le Retrait",
    payoutGateway: "Sélectionner la Passerelle de Paiement",
    bankWire: "Virement Bancaire International",
    cryptoWallet: "Portefeuille Réseau Crypto",
    enterMobile: "Entrez Numéro Mobile / ID Portefeuille",
    cryptoAddress: "Collez l'adresse de votre portefeuille réseau",
    securityPassword: "Entrez le mot de passe de sécurité",
    transferTitle: "Transfert",
    transferFunds: "Transférer des Fonds",
    fromAccount: "Compte Source",
    toAccount: "Compte Destination",
    transferAmount: "Montant du Transfert",
    confirm: "Confirmer",
    inviteTitle: "Inviter des Amis",
    myReferrals: "Mes Parrainages",
    copyLink: "Copier le Lien d'Invitation",
    shareCode: "Partager le Code",
    totalReferrals: "Total des Parrainages",
    accountHelp: "Aide au Compte",
    manageProfile: "Gérer le profil",
    addFunds: "Ajouter des fonds en toute sécurité",
    payoutRequests: "Demandes de paiement",
    generalSupport: "Support Général",
    wealthTitle: "Richesse",
    noSubscriptions: "Aucun abonnement",
    dailyIncome: "Revenu Quotidien",
    duration: "Durée",
    minimum: "Minimum",
    subscribe: "S'abonner",
    days: "Jours",
    copySquare: "Place de Copie",
    professional: "Professionnel",
    amateur: "Amateur",
    myMaster: "Mon Maître",
    profitRate: "Taux de Profit",
    settingsTitle: "Paramètres",
    changePassword: "Changer le mot de passe et les options de sécurité",
    language: "Langue",
    darkMode: "Mode Sombre",
    appVersion: "Version de l'App",
    latest: "Dernière",
    loanTitle: "Prêt",
    applyLoan: "Demander un Prêt",
    loanAmount: "Montant du Prêt",
    repayment: "Remboursement",
    interestRate: "Taux d'Intérêt",
    ordersTitle: "Mes Ordres",
    noOrders: "Aucun ordre trouvé",
    profit: "Profit",
    loss: "Perte",
    status: "Statut",
    symbol: "Symbole",
    orderType: "Type d'Ordre",
    loading: "Chargement...",
    save: "Enregistrer",
    cancel: "Annuler",
    submit: "Soumettre",
    ok: "OK",
    back: "Retour",
    next: "Suivant",
    globalPlatform: "Plateforme financière mondiale de trading intégrée",
  },

  // ─────────────────────────────────────────
  // 7. Deutsch 🇩🇪
  // ─────────────────────────────────────────
  de_DE: {
    flag: "🇩🇪",
    langName: "Deutsch",
    username: "Benutzername",
    password: "Passwort",
    signin: "Anmelden",
    createAccount: "Konto erstellen",
    forgotPassword: "Passwort vergessen?",
    regTitle: "Konto erstellen",
    regSubtitle: "Treten Sie CptMarkets für globalen Handel bei",
    confirmPassword: "Passwort bestätigen",
    inviteCode: "Einladungscode (optional)",
    register: "Registrieren",
    alreadyAccount: "Haben Sie bereits ein Konto?",
    signIn: "Anmelden",
    navHome: "Startseite",
    navMarkets: "Märkte",
    navAssets: "Vermögen",
    navMine: "Profil",
    navTrade: "Handel",
    totalAssets: "Gesamtvermögen (USD)",
    floatingPL: "Schwebendes G/V",
    equity: "Eigenkapital",
    deposit: "Einzahlung",
    withdraw: "Auszahlung",
    transfer: "Überweisung",
    support: "Support",
    copyTrade: "Handel Kopieren",
    loan: "Darlehen",
    wealth: "Vermögen",
    mining: "Mining",
    invite: "Einladen",
    hotMarkets: "Beliebte Märkte",
    viewAll: "Alle Anzeigen",
    all: "Alle",
    forex: "Devisen",
    crypto: "Krypto",
    metals: "Metalle",
    indices: "Indizes",
    notifications: "Benachrichtigungen",
    close: "Schließen",
    assetsTitle: "Vermögen",
    available: "Verfügbar",
    frozen: "Eingefroren",
    fundingAccount: "Finanzierungskonto",
    mainWalletBalance: "Hauptguthaben",
    spotAccount: "Spot-Konto",
    spotTradingAssets: "Spot-Handelsvermögen",
    futuresAccount: "Futures-Konto",
    futuresBalance: "Futures-Guthaben",
    myAssets: "Mein Vermögen",
    history: "Verlauf",
    noRecords: "Keine Einträge",
    leverage: "Hebelwirkung",
    convertedLots: "Umgerechnete Lots",
    contractValue: "Vertragswert",
    entryPrice: "Einstiegspreis",
    currentPrice: "Aktueller Preis",
    amount: "Betrag",
    buyUp: "Kaufen (Aufwärts)",
    sellDown: "Verkaufen (Abwärts)",
    openOrders: "Offene Aufträge",
    orderHistory: "Auftragsverlauf",
    todayPL: "Heutiges G/V",
    totalPL: "Gesamt-G/V",
    open: "Offen",
    myOrders: "Meine Aufträge",
    copyTrading: "Handel Kopieren",
    wealthMining: "Vermögen / Mining",
    inviteFriends: "Freunde Einladen",
    walletManagement: "Wallet-Verwaltung",
    security: "Sicherheit",
    announcements: "Ankündigungen",
    signOut: "Abmelden",
    loginPassword: "Anmeldepasswort",
    protectAccount: "Schützen Sie Ihr Konto mit einem sicheren Passwort.",
    accountSecurity: "Kontosicherheit",
    keepAccountSafe: "Halten Sie Ihre Kontoinformationen sicher.",
    securityVerification: "Sicherheitsüberprüfung",
    manageVerification: "Verwalten Sie Ihre Kontoüberprüfungseinstellungen.",
    depositTitle: "Einzahlung",
    fundAccount: "Finanzieren Sie Ihr CptMarkets-Konto",
    depositGuidelines: "Einzahlungsrichtlinien",
    startRequest: "Anfrage starten",
    provideUID: "Geben Sie Ihre Konto-UID an",
    confirmPayment: "Zahlungsdetails bestätigen",
    submitReceipt: "Quittung einreichen",
    officialSupport: "Offiziellen Support-Kanal nutzen",
    onlineCustomerService: "Online-Kundendienst",
    depositAssistance: "Einzahlungshilfe",
    depositInfo: "Einzahlungsinformationen",
    globalWithdrawal: "Globale Fondsauszahlung",
    availableUSDT: "Verfügbares USDT-Guthaben",
    paymentMethod: "Internationale Zahlungsmethode",
    selectPayout: "Auszahlungssystem auswählen",
    enterAmount: "Betrag eingeben",
    confirmWithdrawal: "Auszahlung bestätigen",
    payoutGateway: "Auszahlungsgateway auswählen",
    bankWire: "Internationale Banküberweisung",
    cryptoWallet: "Krypto-Netzwerk-Wallet",
    enterMobile: "Mobilnummer / Wallet-ID eingeben",
    cryptoAddress: "Netzwerk-Wallet-Adresse einfügen",
    securityPassword: "Sicherheitspasswort eingeben",
    transferTitle: "Überweisung",
    transferFunds: "Gelder überweisen",
    fromAccount: "Quellkonto",
    toAccount: "Zielkonto",
    transferAmount: "Überweisungsbetrag",
    confirm: "Bestätigen",
    inviteTitle: "Freunde Einladen",
    myReferrals: "Meine Empfehlungen",
    copyLink: "Einladungslink kopieren",
    shareCode: "Code teilen",
    totalReferrals: "Empfehlungen gesamt",
    accountHelp: "Kontohilfe",
    manageProfile: "Profil verwalten",
    addFunds: "Gelder sicher hinzufügen",
    payoutRequests: "Auszahlungsanfragen",
    generalSupport: "Allgemeiner Support",
    wealthTitle: "Vermögen",
    noSubscriptions: "Keine Abonnements",
    dailyIncome: "Tägliches Einkommen",
    duration: "Dauer",
    minimum: "Minimum",
    subscribe: "Abonnieren",
    days: "Tage",
    copySquare: "Kopierplatz",
    professional: "Professionell",
    amateur: "Amateur",
    myMaster: "Mein Meister",
    profitRate: "Gewinnrate",
    settingsTitle: "Einstellungen",
    changePassword: "Passwort und Sicherheitsoptionen ändern",
    language: "Sprache",
    darkMode: "Dunkelmodus",
    appVersion: "App-Version",
    latest: "Neueste",
    loanTitle: "Darlehen",
    applyLoan: "Darlehen beantragen",
    loanAmount: "Darlehensbetrag",
    repayment: "Rückzahlung",
    interestRate: "Zinssatz",
    ordersTitle: "Meine Aufträge",
    noOrders: "Keine Aufträge gefunden",
    profit: "Gewinn",
    loss: "Verlust",
    status: "Status",
    symbol: "Symbol",
    orderType: "Auftragstyp",
    loading: "Wird geladen...",
    save: "Speichern",
    cancel: "Abbrechen",
    submit: "Absenden",
    ok: "OK",
    back: "Zurück",
    next: "Weiter",
    globalPlatform: "Globale integrierte Finanzhandelsplattform",
  },

  // ─────────────────────────────────────────
  // 8. 中文 🇨🇳
  // ─────────────────────────────────────────
  zh_CN: {
    flag: "🇨🇳",
    langName: "中文",
    username: "用户名",
    password: "密码",
    signin: "登录",
    createAccount: "创建账户",
    forgotPassword: "忘记密码？",
    regTitle: "创建账户",
    regSubtitle: "加入CptMarkets进行全球交易",
    confirmPassword: "确认密码",
    inviteCode: "邀请码（可选）",
    register: "注册",
    alreadyAccount: "已有账户？",
    signIn: "登录",
    navHome: "首页",
    navMarkets: "市场",
    navAssets: "资产",
    navMine: "我的",
    navTrade: "交易",
    totalAssets: "总资产（美元）",
    floatingPL: "浮动盈亏",
    equity: "净值",
    deposit: "存款",
    withdraw: "取款",
    transfer: "转账",
    support: "客服",
    copyTrade: "跟单交易",
    loan: "贷款",
    wealth: "理财",
    mining: "挖矿",
    invite: "邀请",
    hotMarkets: "热门市场",
    viewAll: "查看全部",
    all: "全部",
    forex: "外汇",
    crypto: "加密货币",
    metals: "贵金属",
    indices: "指数",
    notifications: "通知",
    close: "关闭",
    assetsTitle: "资产",
    available: "可用",
    frozen: "冻结",
    fundingAccount: "资金账户",
    mainWalletBalance: "主钱包余额",
    spotAccount: "现货账户",
    spotTradingAssets: "现货交易资产",
    futuresAccount: "期货账户",
    futuresBalance: "期货余额",
    myAssets: "我的资产",
    history: "历史",
    noRecords: "暂无记录",
    leverage: "杠杆",
    convertedLots: "换算手数",
    contractValue: "合约价值",
    entryPrice: "入场价格",
    currentPrice: "当前价格",
    amount: "金额",
    buyUp: "买涨",
    sellDown: "买跌",
    openOrders: "持仓订单",
    orderHistory: "历史订单",
    todayPL: "今日盈亏",
    totalPL: "总盈亏",
    open: "持仓",
    myOrders: "我的订单",
    copyTrading: "跟单交易",
    wealthMining: "理财 / 挖矿",
    inviteFriends: "邀请好友",
    walletManagement: "钱包管理",
    security: "安全",
    announcements: "公告",
    signOut: "退出登录",
    loginPassword: "登录密码",
    protectAccount: "使用安全密码保护您的账户。",
    accountSecurity: "账户安全",
    keepAccountSafe: "保护好您的账户信息。",
    securityVerification: "安全验证",
    manageVerification: "管理您的账户验证设置。",
    depositTitle: "存款",
    fundAccount: "为您的CptMarkets账户充值",
    depositGuidelines: "存款指南",
    startRequest: "开始申请",
    provideUID: "提供您的账户UID",
    confirmPayment: "确认付款详情",
    submitReceipt: "提交收据",
    officialSupport: "使用官方客服渠道",
    onlineCustomerService: "在线客服",
    depositAssistance: "存款协助",
    depositInfo: "存款信息",
    globalWithdrawal: "全球资金提现",
    availableUSDT: "可用USDT余额",
    paymentMethod: "国际付款方式",
    selectPayout: "选择支付系统",
    enterAmount: "输入金额",
    confirmWithdrawal: "确认提现",
    payoutGateway: "选择支付通道",
    bankWire: "国际银行电汇",
    cryptoWallet: "加密网络钱包",
    enterMobile: "输入手机号 / 钱包ID",
    cryptoAddress: "粘贴您的网络钱包地址",
    securityPassword: "输入安全密码",
    transferTitle: "转账",
    transferFunds: "资金转账",
    fromAccount: "转出账户",
    toAccount: "转入账户",
    transferAmount: "转账金额",
    confirm: "确认",
    inviteTitle: "邀请好友",
    myReferrals: "我的推荐",
    copyLink: "复制邀请链接",
    shareCode: "分享码",
    totalReferrals: "总推荐人数",
    accountHelp: "账户帮助",
    manageProfile: "管理资料",
    addFunds: "安全添加资金",
    payoutRequests: "提现申请",
    generalSupport: "一般客服",
    wealthTitle: "理财",
    noSubscriptions: "暂无订阅",
    dailyIncome: "日收益",
    duration: "期限",
    minimum: "最低",
    subscribe: "订阅",
    days: "天",
    copySquare: "跟单广场",
    professional: "专业版",
    amateur: "业余版",
    myMaster: "我的交易员",
    profitRate: "盈利率",
    settingsTitle: "设置",
    changePassword: "修改密码和安全选项",
    language: "语言",
    darkMode: "深色模式",
    appVersion: "应用版本",
    latest: "最新",
    loanTitle: "贷款",
    applyLoan: "申请贷款",
    loanAmount: "贷款金额",
    repayment: "还款",
    interestRate: "利率",
    ordersTitle: "我的订单",
    noOrders: "暂无订单",
    profit: "盈利",
    loss: "亏损",
    status: "状态",
    symbol: "交易对",
    orderType: "订单类型",
    loading: "加载中...",
    save: "保存",
    cancel: "取消",
    submit: "提交",
    ok: "确定",
    back: "返回",
    next: "下一步",
    globalPlatform: "全球综合金融交易平台",
  },

  // ─────────────────────────────────────────
  // 9. 日本語 🇯🇵
  // ─────────────────────────────────────────
  ja_JP: {
    flag: "🇯🇵",
    langName: "日本語",
    username: "ユーザー名",
    password: "パスワード",
    signin: "サインイン",
    createAccount: "アカウント作成",
    forgotPassword: "パスワードをお忘れですか？",
    regTitle: "アカウント作成",
    regSubtitle: "グローバルトレーディングにCptMarketsに参加",
    confirmPassword: "パスワードの確認",
    inviteCode: "招待コード（任意）",
    register: "登録",
    alreadyAccount: "すでにアカウントをお持ちですか？",
    signIn: "サインイン",
    navHome: "ホーム",
    navMarkets: "市場",
    navAssets: "資産",
    navMine: "マイページ",
    navTrade: "取引",
    totalAssets: "総資産（USD）",
    floatingPL: "変動損益",
    equity: "純資産",
    deposit: "入金",
    withdraw: "出金",
    transfer: "送金",
    support: "サポート",
    copyTrade: "コピートレード",
    loan: "ローン",
    wealth: "ウェルス",
    mining: "マイニング",
    invite: "招待",
    hotMarkets: "注目市場",
    viewAll: "すべて見る",
    all: "すべて",
    forex: "FX",
    crypto: "暗号資産",
    metals: "貴金属",
    indices: "指数",
    notifications: "通知",
    close: "閉じる",
    assetsTitle: "資産",
    available: "利用可能",
    frozen: "凍結",
    fundingAccount: "資金口座",
    mainWalletBalance: "メインウォレット残高",
    spotAccount: "現物口座",
    spotTradingAssets: "現物取引資産",
    futuresAccount: "先物口座",
    futuresBalance: "先物残高",
    myAssets: "マイ資産",
    history: "履歴",
    noRecords: "記録なし",
    leverage: "レバレッジ",
    convertedLots: "換算ロット",
    contractValue: "契約価値",
    entryPrice: "エントリー価格",
    currentPrice: "現在価格",
    amount: "金額",
    buyUp: "買い（上昇）",
    sellDown: "売り（下落）",
    openOrders: "未決注文",
    orderHistory: "注文履歴",
    todayPL: "本日の損益",
    totalPL: "累計損益",
    open: "オープン",
    myOrders: "マイ注文",
    copyTrading: "コピートレード",
    wealthMining: "ウェルス / マイニング",
    inviteFriends: "友達を招待",
    walletManagement: "ウォレット管理",
    security: "セキュリティ",
    announcements: "お知らせ",
    signOut: "サインアウト",
    loginPassword: "ログインパスワード",
    protectAccount: "安全なパスワードでアカウントを保護してください。",
    accountSecurity: "アカウントセキュリティ",
    keepAccountSafe: "アカウント情報を安全に保ってください。",
    securityVerification: "セキュリティ確認",
    manageVerification: "アカウント確認設定を管理してください。",
    depositTitle: "入金",
    fundAccount: "CptMarketsアカウントに入金",
    depositGuidelines: "入金ガイドライン",
    startRequest: "申請開始",
    provideUID: "アカウントUIDを提供",
    confirmPayment: "支払い詳細の確認",
    submitReceipt: "領収書の提出",
    officialSupport: "公式サポートチャンネルを使用",
    onlineCustomerService: "オンラインカスタマーサービス",
    depositAssistance: "入金サポート",
    depositInfo: "入金情報",
    globalWithdrawal: "グローバル資金出金",
    availableUSDT: "利用可能なUSDT残高",
    paymentMethod: "国際支払い方法",
    selectPayout: "支払いシステムを選択",
    enterAmount: "金額を入力",
    confirmWithdrawal: "出金を確認",
    payoutGateway: "支払いゲートウェイを選択",
    bankWire: "国際銀行送金",
    cryptoWallet: "暗号ネットワークウォレット",
    enterMobile: "携帯番号 / ウォレットIDを入力",
    cryptoAddress: "ネットワークウォレットアドレスを貼り付け",
    securityPassword: "セキュリティパスワードを入力",
    transferTitle: "送金",
    transferFunds: "資金移動",
    fromAccount: "送金元口座",
    toAccount: "送金先口座",
    transferAmount: "送金額",
    confirm: "確認",
    inviteTitle: "友達を招待",
    myReferrals: "マイ紹介",
    copyLink: "招待リンクをコピー",
    shareCode: "コードをシェア",
    totalReferrals: "紹介合計",
    accountHelp: "アカウントヘルプ",
    manageProfile: "プロフィール管理",
    addFunds: "安全に資金を追加",
    payoutRequests: "出金申請",
    generalSupport: "一般サポート",
    wealthTitle: "ウェルス",
    noSubscriptions: "サブスクリプションなし",
    dailyIncome: "日次収益",
    duration: "期間",
    minimum: "最低額",
    subscribe: "申し込む",
    days: "日",
    copySquare: "コピースクエア",
    professional: "プロフェッショナル",
    amateur: "アマチュア",
    myMaster: "マイマスター",
    profitRate: "利益率",
    settingsTitle: "設定",
    changePassword: "パスワードとセキュリティオプションを変更",
    language: "言語",
    darkMode: "ダークモード",
    appVersion: "アプリバージョン",
    latest: "最新",
    loanTitle: "ローン",
    applyLoan: "ローン申請",
    loanAmount: "ローン金額",
    repayment: "返済",
    interestRate: "金利",
    ordersTitle: "マイ注文",
    noOrders: "注文が見つかりません",
    profit: "利益",
    loss: "損失",
    status: "ステータス",
    symbol: "銘柄",
    orderType: "注文タイプ",
    loading: "読み込み中...",
    save: "保存",
    cancel: "キャンセル",
    submit: "送信",
    ok: "OK",
    back: "戻る",
    next: "次へ",
    globalPlatform: "グローバル総合金融取引プラットフォーム",
  },

  // ─────────────────────────────────────────
  // 10. Italiano 🇮🇹
  // ─────────────────────────────────────────
  it_IT: {
    flag: "🇮🇹",
    langName: "Italiano",
    username: "Nome utente",
    password: "Password",
    signin: "Accedi",
    createAccount: "Crea account",
    forgotPassword: "Password dimenticata?",
    regTitle: "Crea account",
    regSubtitle: "Unisciti a CptMarkets per il trading globale",
    confirmPassword: "Conferma password",
    inviteCode: "Codice invito (facoltativo)",
    register: "Registrati",
    alreadyAccount: "Hai già un account?",
    signIn: "Accedi",
    navHome: "Home",
    navMarkets: "Mercati",
    navAssets: "Attività",
    navMine: "Profilo",
    navTrade: "Trading",
    totalAssets: "Attività Totali (USD)",
    floatingPL: "P/P Variabile",
    equity: "Patrimonio",
    deposit: "Deposito",
    withdraw: "Prelievo",
    transfer: "Trasferimento",
    support: "Supporto",
    copyTrade: "Copia Trade",
    loan: "Prestito",
    wealth: "Ricchezza",
    mining: "Mining",
    invite: "Invita",
    hotMarkets: "Mercati Caldi",
    viewAll: "Vedi Tutto",
    all: "Tutto",
    forex: "Forex",
    crypto: "Cripto",
    metals: "Metalli",
    indices: "Indici",
    notifications: "Notifiche",
    close: "Chiudi",
    assetsTitle: "Attività",
    available: "Disponibile",
    frozen: "Congelato",
    fundingAccount: "Conto di Finanziamento",
    mainWalletBalance: "Saldo Principale del Portafoglio",
    spotAccount: "Conto Spot",
    spotTradingAssets: "Attività di Trading Spot",
    futuresAccount: "Conto Futures",
    futuresBalance: "Saldo Futures",
    myAssets: "Le Mie Attività",
    history: "Cronologia",
    noRecords: "Nessun record",
    leverage: "Leva",
    convertedLots: "Lotti Convertiti",
    contractValue: "Valore del Contratto",
    entryPrice: "Prezzo di Entrata",
    currentPrice: "Prezzo Attuale",
    amount: "Importo",
    buyUp: "Acquista (Rialzo)",
    sellDown: "Vendi (Ribasso)",
    openOrders: "Ordini Aperti",
    orderHistory: "Cronologia Ordini",
    todayPL: "P/P Oggi",
    totalPL: "P/P Totale",
    open: "Aperto",
    myOrders: "I Miei Ordini",
    copyTrading: "Copia Trading",
    wealthMining: "Ricchezza / Mining",
    inviteFriends: "Invita Amici",
    walletManagement: "Gestione Portafoglio",
    security: "Sicurezza",
    announcements: "Annunci",
    signOut: "Esci",
    loginPassword: "Password di Accesso",
    protectAccount: "Proteggi il tuo account con una password sicura.",
    accountSecurity: "Sicurezza Account",
    keepAccountSafe: "Mantieni al sicuro le informazioni del tuo account.",
    securityVerification: "Verifica di Sicurezza",
    manageVerification: "Gestisci le impostazioni di verifica del tuo account.",
    depositTitle: "Deposito",
    fundAccount: "Finanzia il tuo Account CptMarkets",
    depositGuidelines: "Istruzioni per il Deposito",
    startRequest: "Inizia la Richiesta",
    provideUID: "Fornisci il tuo UID Account",
    confirmPayment: "Conferma i Dettagli di Pagamento",
    submitReceipt: "Invia la Ricevuta",
    officialSupport: "Usa il Canale di Supporto Ufficiale",
    onlineCustomerService: "Servizio Clienti Online",
    depositAssistance: "Assistenza Deposito",
    depositInfo: "Informazioni sul Deposito",
    globalWithdrawal: "Prelievo Fondi Globale",
    availableUSDT: "Saldo USDT Disponibile",
    paymentMethod: "Metodo di Pagamento Internazionale",
    selectPayout: "Seleziona sistema di pagamento",
    enterAmount: "Inserisci il tuo importo",
    confirmWithdrawal: "Conferma Prelievo",
    payoutGateway: "Seleziona Gateway di Pagamento",
    bankWire: "Bonifico Bancario Internazionale",
    cryptoWallet: "Portafoglio Rete Cripto",
    enterMobile: "Inserisci Numero Mobile / ID Portafoglio",
    cryptoAddress: "Incolla l'indirizzo del portafoglio di rete",
    securityPassword: "Inserisci la password di sicurezza",
    transferTitle: "Trasferimento",
    transferFunds: "Trasferisci Fondi",
    fromAccount: "Conto di Origine",
    toAccount: "Conto di Destinazione",
    transferAmount: "Importo Trasferimento",
    confirm: "Conferma",
    inviteTitle: "Invita Amici",
    myReferrals: "I Miei Referral",
    copyLink: "Copia Link Invito",
    shareCode: "Condividi Codice",
    totalReferrals: "Totale Referral",
    accountHelp: "Aiuto Account",
    manageProfile: "Gestisci profilo",
    addFunds: "Aggiungi fondi in sicurezza",
    payoutRequests: "Richieste di pagamento",
    generalSupport: "Supporto Generale",
    wealthTitle: "Ricchezza",
    noSubscriptions: "Nessun abbonamento",
    dailyIncome: "Reddito Giornaliero",
    duration: "Durata",
    minimum: "Minimo",
    subscribe: "Iscriviti",
    days: "Giorni",
    copySquare: "Piazza Copia",
    professional: "Professionale",
    amateur: "Dilettante",
    myMaster: "Il Mio Maestro",
    profitRate: "Tasso di Profitto",
    settingsTitle: "Impostazioni",
    changePassword: "Cambia password e opzioni di sicurezza",
    language: "Lingua",
    darkMode: "Modalità Scura",
    appVersion: "Versione App",
    latest: "Ultima",
    loanTitle: "Prestito",
    applyLoan: "Richiedi Prestito",
    loanAmount: "Importo Prestito",
    repayment: "Rimborso",
    interestRate: "Tasso di Interesse",
    ordersTitle: "I Miei Ordini",
    noOrders: "Nessun ordine trovato",
    profit: "Profitto",
    loss: "Perdita",
    status: "Stato",
    symbol: "Simbolo",
    orderType: "Tipo Ordine",
    loading: "Caricamento...",
    save: "Salva",
    cancel: "Annulla",
    submit: "Invia",
    ok: "OK",
    back: "Indietro",
    next: "Avanti",
    globalPlatform: "Piattaforma finanziaria globale di trading integrata",
  },

};
// ============================================================
//  END OF lang.js
//  Usage: include this file before translator.js in every HTML page
// ============================================================
