// ============================================================
//  CptMarkets — lang.js
//  সম্পূর্ণ ওয়েবসাইটের জন্য ১১টি ভাষা
//  11 International Languages for all pages
// ============================================================

const languageData = {

  // ─────────────────────────────────────────
  // 1. English (UK) 🇬🇧
  // ─────────────────────────────────────────
  en_UK: {
    flag: "🇬🇧",
    langName: "English (UK)",

    // LOGIN
    username: "Username",
    password: "Password",
    signin: "Go to Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",

    // REGISTER
    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",

    // NAVIGATION (Bottom bar)
    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Mine",
    navTrade: "Trade",

    // DASHBOARD
    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",

    // MARKETS
    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",

    // ASSETS
    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",

    // TRADE
    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",

    // MINE (Profile)
    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",

    // DEPOSIT
    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",

    // WITHDRAW
    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",

    // TRANSFER
    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",

    // INVITE
    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",

    // SUPPORT
    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",

    // INVESTMENT / WEALTH
    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",

    // COPY TRADE
    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",

    // SETTINGS
    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",

    // LOAN
    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",

    // ORDERS
    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",

    // COMMON
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },

  // ─────────────────────────────────────────
  // 2. বাংলা 🇧🇩
  // ─────────────────────────────────────────
  bn_BD: {
    flag: "🇧🇩",
    langName: "বাংলা",

    username: "ইউজারনেম",
    password: "পাসওয়ার্ড",
    signin: "লগইন করুন",
    createAccount: "অ্যাকাউন্ট খুলুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",

    regTitle: "অ্যাকাউন্ট তৈরি করুন",
    regSubtitle: "বৈশ্বিক ট্রেডিংয়ের জন্য CptMarkets-এ যোগ দিন",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    inviteCode: "আমন্ত্রণ কোড (ঐচ্ছিক)",
    register: "নিবন্ধন করুন",
    alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    signIn: "সাইন ইন",

    navHome: "হোম",
    navMarkets: "মার্কেট",
    navAssets: "সম্পদ",
    navMine: "প্রোফাইল",
    navTrade: "ট্রেড",

    totalAssets: "মোট সম্পদ (USD)",
    floatingPL: "ভাসমান লাভ/লোকসান",
    equity: "ইকুইটি",
    deposit: "জমা",
    withdraw: "উত্তোলন",
    transfer: "ট্রান্সফার",
    support: "সাপোর্ট",
    copyTrade: "কপি ট্রেড",
    loan: "ঋণ",
    wealth: "ওয়েলথ",
    mining: "মাইনিং",
    invite: "আমন্ত্রণ",
    hotMarkets: "হট মার্কেট",
    viewAll: "সব দেখুন",

    all: "সব",
    forex: "ফরেক্স",
    crypto: "ক্রিপ্টো",
    metals: "ধাতু",
    indices: "সূচক",
    notifications: "বিজ্ঞপ্তি",
    close: "বন্ধ করুন",

    assetsTitle: "সম্পদ",
    available: "উপলব্ধ",
    frozen: "জমাট",
    fundingAccount: "ফান্ডিং অ্যাকাউন্ট",
    mainWalletBalance: "মূল ওয়ালেট ব্যালেন্স",
    spotAccount: "স্পট অ্যাকাউন্ট",
    spotTradingAssets: "স্পট ট্রেডিং সম্পদ",
    futuresAccount: "ফিউচার্স অ্যাকাউন্ট",
    futuresBalance: "ফিউচার্স ব্যালেন্স",
    myAssets: "আমার সম্পদ",
    history: "ইতিহাস",
    noRecords: "কোনো রেকর্ড নেই",

    leverage: "লিভারেজ",
    convertedLots: "রূপান্তরিত লট",
    contractValue: "চুক্তির মূল্য",
    entryPrice: "প্রবেশ মূল্য",
    currentPrice: "বর্তমান মূল্য",
    amount: "পরিমাণ",
    buyUp: "কিনুন (আপ)",
    sellDown: "বিক্রি করুন (ডাউন)",
    openOrders: "খোলা অর্ডার",
    orderHistory: "অর্ডার ইতিহাস",

    todayPL: "আজকের লাভ/লোকসান",
    totalPL: "মোট লাভ/লোকসান",
    open: "খোলা",
    myOrders: "আমার অর্ডার",
    copyTrading: "কপি ট্রেডিং",
    wealthMining: "ওয়েলথ / মাইনিং",
    inviteFriends: "বন্ধু আমন্ত্রণ",
    walletManagement: "ওয়ালেট ম্যানেজমেন্ট",
    security: "নিরাপত্তা",
    announcements: "ঘোষণা",
    signOut: "সাইন আউট",
    loginPassword: "লগইন পাসওয়ার্ড",
    protectAccount: "একটি শক্তিশালী পাসওয়ার্ড দিয়ে অ্যাকাউন্ট সুরক্ষিত রাখুন।",
    accountSecurity: "অ্যাকাউন্ট নিরাপত্তা",
    keepAccountSafe: "আপনার অ্যাকাউন্টের তথ্য সুরক্ষিত রাখুন।",
    securityVerification: "নিরাপত্তা যাচাইকরণ",
    manageVerification: "আপনার অ্যাকাউন্ট যাচাইকরণ সেটিংস পরিচালনা করুন।",

    depositTitle: "জমা",
    fundAccount: "আপনার CptMarkets অ্যাকাউন্টে অর্থ যোগ করুন",
    depositGuidelines: "জমার নির্দেশিকা",
    startRequest: "অনুরোধ শুরু করুন",
    provideUID: "আপনার অ্যাকাউন্ট UID দিন",
    confirmPayment: "পেমেন্টের বিবরণ নিশ্চিত করুন",
    submitReceipt: "আপনার রসিদ জমা দিন",
    officialSupport: "অফিসিয়াল সাপোর্ট চ্যানেল ব্যবহার করুন",
    onlineCustomerService: "অনলাইন গ্রাহক সেবা",
    depositAssistance: "জমার সহায়তা",
    depositInfo: "জমার তথ্য",

    globalWithdrawal: "গ্লোবাল ফান্ড উত্তোলন",
    availableUSDT: "উপলব্ধ USDT ব্যালেন্স",
    paymentMethod: "আন্তর্জাতিক পেমেন্ট পদ্ধতি",
    selectPayout: "পেআউট সিস্টেম নির্বাচন করুন",
    enterAmount: "আপনার পরিমাণ লিখুন",
    confirmWithdrawal: "উত্তোলন নিশ্চিত করুন",
    payoutGateway: "পেআউট গেটওয়ে নির্বাচন করুন",
    bankWire: "আন্তর্জাতিক ব্যাংক ওয়্যার ট্রান্সফার",
    cryptoWallet: "ক্রিপ্টো নেটওয়ার্ক ওয়ালেট",
    enterMobile: "মোবাইল নম্বর / ওয়ালেট আইডি লিখুন",
    cryptoAddress: "আপনার নেটওয়ার্ক ওয়ালেট ঠিকানা পেস্ট করুন",
    securityPassword: "নিরাপত্তা পাসওয়ার্ড লিখুন",

    transferTitle: "ট্রান্সফার",
    transferFunds: "তহবিল স্থানান্তর",
    fromAccount: "উৎস অ্যাকাউন্ট",
    toAccount: "গন্তব্য অ্যাকাউন্ট",
    transferAmount: "স্থানান্তর পরিমাণ",
    confirm: "নিশ্চিত করুন",

    inviteTitle: "বন্ধু আমন্ত্রণ",
    myReferrals: "আমার রেফারেল",
    copyLink: "আমন্ত্রণ লিংক কপি করুন",
    shareCode: "কোড শেয়ার করুন",
    totalReferrals: "মোট রেফারেল",

    accountHelp: "অ্যাকাউন্ট সহায়তা",
    manageProfile: "প্রোফাইল পরিচালনা",
    addFunds: "নিরাপদে অর্থ যোগ করুন",
    payoutRequests: "পেআউট অনুরোধ",
    generalSupport: "সাধারণ সাপোর্ট",

    wealthTitle: "ওয়েলথ",
    noSubscriptions: "কোনো সাবস্ক্রিপশন নেই",
    dailyIncome: "দৈনিক আয়",
    duration: "মেয়াদ",
    minimum: "সর্বনিম্ন",
    subscribe: "সাবস্ক্রাইব",
    days: "দিন",

    copySquare: "কপি স্কোয়ার",
    professional: "প্রফেশনাল",
    amateur: "অ্যামেচার",
    myMaster: "আমার মাস্টার",
    profitRate: "মুনাফার হার",

    settingsTitle: "সেটিংস",
    changePassword: "পাসওয়ার্ড ও নিরাপত্তা পরিবর্তন",
    language: "ভাষা",
    darkMode: "ডার্ক মোড",
    appVersion: "অ্যাপ ভার্সন",
    latest: "সর্বশেষ",

    loanTitle: "ঋণ",
    applyLoan: "ঋণের জন্য আবেদন",
    loanAmount: "ঋণের পরিমাণ",
    repayment: "পরিশোধ",
    interestRate: "সুদের হার",

    ordersTitle: "আমার অর্ডার",
    noOrders: "কোনো অর্ডার পাওয়া যায়নি",
    profit: "লাভ",
    loss: "লোকসান",
    status: "অবস্থা",
    symbol: "সিম্বল",
    orderType: "অর্ডারের ধরন",

    loading: "লোড হচ্ছে...",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    submit: "জমা দিন",
    ok: "ঠিক আছে",
    back: "পিছনে",
    next: "পরবর্তী",
    globalPlatform: "গ্লোবাল ইন্টিগ্রেটেড ফিনান্সিয়াল ট্রেডিং প্ল্যাটফর্ম",
  },

  // ─────────────────────────────────────────
  // 3. हिन्दी 🇮🇳
  // ─────────────────────────────────────────
  hi_IN: {
    flag: "🇮🇳",
    langName: "हिन्दी",

    username: "यूजरनेम",
    password: "पासवर्ड",
    signin: "साइन इन करें",
    createAccount: "खाता बनाएं",
    forgotPassword: "पासवर्ड भूल गए?",

    regTitle: "खाता बनाएं",
    regSubtitle: "वैश्विक ट्रेडिंग के लिए CptMarkets से जुड़ें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    inviteCode: "आमंत्रण कोड (वैकल्पिक)",
    register: "पंजीकरण करें",
    alreadyAccount: "पहले से खाता है?",
    signIn: "साइन इन",

    navHome: "होम",
    navMarkets: "बाज़ार",
    navAssets: "संपत्ति",
    navMine: "प्रोफ़ाइल",
    navTrade: "ट्रेड",

    totalAssets: "कुल संपत्ति (USD)",
    floatingPL: "फ्लोटिंग लाभ/हानि",
    equity: "इक्विटी",
    deposit: "जमा",
    withdraw: "निकासी",
    transfer: "ट्रांसफर",
    support: "सहायता",
    copyTrade: "कॉपी ट्रेड",
    loan: "ऋण",
    wealth: "वेल्थ",
    mining: "माइनिंग",
    invite: "आमंत्रित करें",
    hotMarkets: "हॉट मार्केट",
    viewAll: "सब देखें",

    all: "सभी",
    forex: "फॉरेक्स",
    crypto: "क्रिप्टो",
    metals: "धातु",
    indices: "सूचकांक",
    notifications: "सूचनाएं",
    close: "बंद करें",

    assetsTitle: "संपत्ति",
    available: "उपलब्ध",
    frozen: "फ्रोज़न",
    fundingAccount: "फंडिंग खाता",
    mainWalletBalance: "मुख्य वॉलेट बैलेंस",
    spotAccount: "स्पॉट खाता",
    spotTradingAssets: "स्पॉट ट्रेडिंग संपत्ति",
    futuresAccount: "फ्यूचर्स खाता",
    futuresBalance: "फ्यूचर्स बैलेंस",
    myAssets: "मेरी संपत्ति",
    history: "इतिहास",
    noRecords: "कोई रिकॉर्ड नहीं",

    leverage: "लीवरेज",
    convertedLots: "परिवर्तित लॉट",
    contractValue: "अनुबंध मूल्य",
    entryPrice: "प्रवेश मूल्य",
    currentPrice: "वर्तमान मूल्य",
    amount: "राशि",
    buyUp: "खरीदें (अप)",
    sellDown: "बेचें (डाउन)",
    openOrders: "खुले ऑर्डर",
    orderHistory: "ऑर्डर इतिहास",

    todayPL: "आज का लाभ/हानि",
    totalPL: "कुल लाभ/हानि",
    open: "खुला",
    myOrders: "मेरे ऑर्डर",
    copyTrading: "कॉपी ट्रेडिंग",
    wealthMining: "वेल्थ / माइनिंग",
    inviteFriends: "दोस्तों को आमंत्रित करें",
    walletManagement: "वॉलेट प्रबंधन",
    security: "सुरक्षा",
    announcements: "घोषणाएं",
    signOut: "साइन आउट",
    loginPassword: "लॉगिन पासवर्ड",
    protectAccount: "एक सुरक्षित पासवर्ड से अपना खाता सुरक्षित रखें।",
    accountSecurity: "खाता सुरक्षा",
    keepAccountSafe: "अपनी खाता जानकारी सुरक्षित रखें।",
    securityVerification: "सुरक्षा सत्यापन",
    manageVerification: "अपने खाता सत्यापन सेटिंग्स प्रबंधित करें।",

    depositTitle: "जमा",
    fundAccount: "अपने CptMarkets खाते में फंड करें",
    depositGuidelines: "जमा दिशानिर्देश",
    startRequest: "अनुरोध शुरू करें",
    provideUID: "अपना खाता UID दें",
    confirmPayment: "भुगतान विवरण की पुष्टि करें",
    submitReceipt: "अपनी रसीद जमा करें",
    officialSupport: "आधिकारिक सहायता चैनल का उपयोग करें",
    onlineCustomerService: "ऑनलाइन ग्राहक सेवा",
    depositAssistance: "जमा सहायता",
    depositInfo: "जमा जानकारी",

    globalWithdrawal: "वैश्विक फंड निकासी",
    availableUSDT: "उपलब्ध USDT बैलेंस",
    paymentMethod: "अंतर्राष्ट्रीय भुगतान विधि",
    selectPayout: "पेआउट सिस्टम चुनें",
    enterAmount: "अपनी राशि दर्ज करें",
    confirmWithdrawal: "निकासी की पुष्टि करें",
    payoutGateway: "पेआउट गेटवे चुनें",
    bankWire: "अंतर्राष्ट्रीय बैंक वायर ट्रांसफर",
    cryptoWallet: "क्रिप्टो नेटवर्क वॉलेट",
    enterMobile: "मोबाइल नंबर / वॉलेट आईडी दर्ज करें",
    cryptoAddress: "अपना नेटवर्क वॉलेट पता पेस्ट करें",
    securityPassword: "सुरक्षा पासवर्ड दर्ज करें",

    transferTitle: "ट्रांसफर",
    transferFunds: "फंड ट्रांसफर",
    fromAccount: "स्रोत खाता",
    toAccount: "गंतव्य खाता",
    transferAmount: "ट्रांसफर राशि",
    confirm: "पुष्टि करें",

    inviteTitle: "दोस्तों को आमंत्रित करें",
    myReferrals: "मेरे रेफरल",
    copyLink: "आमंत्रण लिंक कॉपी करें",
    shareCode: "कोड शेयर करें",
    totalReferrals: "कुल रेफरल",

    accountHelp: "खाता सहायता",
    manageProfile: "प्रोफ़ाइल प्रबंधित करें",
    addFunds: "सुरक्षित रूप से फंड जोड़ें",
    payoutRequests: "पेआउट अनुरोध",
    generalSupport: "सामान्य सहायता",

    wealthTitle: "वेल्थ",
    noSubscriptions: "कोई सदस्यता नहीं",
    dailyIncome: "दैनिक आय",
    duration: "अवधि",
    minimum: "न्यूनतम",
    subscribe: "सदस्यता लें",
    days: "दिन",

    copySquare: "कॉपी स्क्वायर",
    professional: "प्रोफेशनल",
    amateur: "शौकिया",
    myMaster: "मेरा मास्टर",
    profitRate: "लाभ दर",

    settingsTitle: "सेटिंग्स",
    changePassword: "पासवर्ड और सुरक्षा विकल्प बदलें",
    language: "भाषा",
    darkMode: "डार्क मोड",
    appVersion: "ऐप वर्जन",
    latest: "नवीनतम",

    loanTitle: "ऋण",
    applyLoan: "ऋण के लिए आवेदन करें",
    loanAmount: "ऋण राशि",
    repayment: "पुनर्भुगतान",
    interestRate: "ब्याज दर",

    ordersTitle: "मेरे ऑर्डर",
    noOrders: "कोई ऑर्डर नहीं मिला",
    profit: "लाभ",
    loss: "हानि",
    status: "स्थिति",
    symbol: "सिम्बल",
    orderType: "ऑर्डर प्रकार",

    loading: "लोड हो रहा है...",
    save: "सहेजें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    ok: "ठीक है",
    back: "वापस",
    next: "अगला",
    globalPlatform: "वैश्विक एकीकृत वित्तीय ट्रेडिंग प्लेटफॉर्म",
  },

  // ─────────────────────────────────────────
  // 4. English (US) 🇺🇸
  // ─────────────────────────────────────────
  en_US: {
    flag: "🇺🇸",
    langName: "English (US)",

    username: "Username",
    password: "Password",
    signin: "Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",

    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",

    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Profile",
    navTrade: "Trade",

    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",

    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",

    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",

    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",

    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",

    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",

    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",

    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",

    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",

    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",

    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",

    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",

    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",

    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",

    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",

    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },
  // ============================================================
//  CptMarkets — lang.js
//  সম্পূর্ণ ওয়েবসাইটের জন্য ১১টি ভাষা
//  11 International Languages for all pages
// ============================================================

const languageData = {

  // ─────────────────────────────────────────
  // 1. English (UK) 🇬🇧
  // ─────────────────────────────────────────
  en_UK: {
    flag: "🇬🇧",
    langName: "English (UK)",

    // LOGIN
    username: "Username",
    password: "Password",
    signin: "Go to Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",

    // REGISTER
    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",

    // NAVIGATION (Bottom bar)
    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Mine",
    navTrade: "Trade",

    // DASHBOARD
    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",

    // MARKETS
    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",

    // ASSETS
    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",

    // TRADE
    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",

    // MINE (Profile)
    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",

    // DEPOSIT
    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",

    // WITHDRAW
    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",

    // TRANSFER
    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",

    // INVITE
    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",

    // SUPPORT
    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",

    // INVESTMENT / WEALTH
    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",

    // COPY TRADE
    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",

    // SETTINGS
    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",

    // LOAN
    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",

    // ORDERS
    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",

    // COMMON
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },

  // ─────────────────────────────────────────
  // 2. বাংলা 🇧🇩
  // ─────────────────────────────────────────
  bn_BD: {
    flag: "🇧🇩",
    langName: "বাংলা",

    username: "ইউজারনেম",
    password: "পাসওয়ার্ড",
    signin: "লগইন করুন",
    createAccount: "অ্যাকাউন্ট খুলুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",

    regTitle: "অ্যাকাউন্ট তৈরি করুন",
    regSubtitle: "বৈশ্বিক ট্রেডিংয়ের জন্য CptMarkets-এ যোগ দিন",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    inviteCode: "আমন্ত্রণ কোড (ঐচ্ছিক)",
    register: "নিবন্ধন করুন",
    alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    signIn: "সাইন ইন",

    navHome: "হোম",
    navMarkets: "মার্কেট",
    navAssets: "সম্পদ",
    navMine: "প্রোফাইল",
    navTrade: "ট্রেড",

    totalAssets: "মোট সম্পদ (USD)",
    floatingPL: "ভাসমান লাভ/লোকসান",
    equity: "ইকুইটি",
    deposit: "জমা",
    withdraw: "উত্তোলন",
    transfer: "ট্রান্সফার",
    support: "সাপোর্ট",
    copyTrade: "কপি ট্রেড",
    loan: "ঋণ",
    wealth: "ওয়েলথ",
    mining: "মাইনিং",
    invite: "আমন্ত্রণ",
    hotMarkets: "হট মার্কেট",
    viewAll: "সব দেখুন",

    all: "সব",
    forex: "ফরেক্স",
    crypto: "ক্রিপ্টো",
    metals: "ধাতু",
    indices: "সূচক",
    notifications: "বিজ্ঞপ্তি",
    close: "বন্ধ করুন",

    assetsTitle: "সম্পদ",
    available: "উপলব্ধ",
    frozen: "জমাট",
    fundingAccount: "ফান্ডিং অ্যাকাউন্ট",
    mainWalletBalance: "মূল ওয়ালেট ব্যালেন্স",
    spotAccount: "স্পট অ্যাকাউন্ট",
    spotTradingAssets: "স্পট ট্রেডিং সম্পদ",
    futuresAccount: "ফিউচার্স অ্যাকাউন্ট",
    futuresBalance: "ফিউচার্স ব্যালেন্স",
    myAssets: "আমার সম্পদ",
    history: "ইতিহাস",
    noRecords: "কোনো রেকর্ড নেই",

    leverage: "লিভারেজ",
    convertedLots: "রূপান্তরিত লট",
    contractValue: "চুক্তির মূল্য",
    entryPrice: "প্রবেশ মূল্য",
    currentPrice: "বর্তমান মূল্য",
    amount: "পরিমাণ",
    buyUp: "কিনুন (আপ)",
    sellDown: "বিক্রি করুন (ডাউন)",
    openOrders: "খোলা অর্ডার",
    orderHistory: "অর্ডার ইতিহাস",

    todayPL: "আজকের লাভ/লোকসান",
    totalPL: "মোট লাভ/লোকসান",
    open: "খোলা",
    myOrders: "আমার অর্ডার",
    copyTrading: "কপি ট্রেডিং",
    wealthMining: "ওয়েলথ / মাইনিং",
    inviteFriends: "বন্ধু আমন্ত্রণ",
    walletManagement: "ওয়ালেট ম্যানেজমেন্ট",
    security: "নিরাপত্তা",
    announcements: "ঘোষণা",
    signOut: "সাইন আউট",
    loginPassword: "লগইন পাসওয়ার্ড",
    protectAccount: "একটি শক্তিশালী পাসওয়ার্ড দিয়ে অ্যাকাউন্ট সুরক্ষিত রাখুন।",
    accountSecurity: "অ্যাকাউন্ট নিরাপত্তা",
    keepAccountSafe: "আপনার অ্যাকাউন্টের তথ্য সুরক্ষিত রাখুন।",
    securityVerification: "নিরাপত্তা যাচাইকরণ",
    manageVerification: "আপনার অ্যাকাউন্ট যাচাইকরণ সেটিংস পরিচালনা করুন।",

    depositTitle: "জমা",
    fundAccount: "আপনার CptMarkets অ্যাকাউন্টে অর্থ যোগ করুন",
    depositGuidelines: "জমার নির্দেশিকা",
    startRequest: "অনুরোধ শুরু করুন",
    provideUID: "আপনার অ্যাকাউন্ট UID দিন",
    confirmPayment: "পেমেন্টের বিবরণ নিশ্চিত করুন",
    submitReceipt: "আপনার রসিদ জমা দিন",
    officialSupport: "অফিসিয়াল সাপোর্ট চ্যানেল ব্যবহার করুন",
    onlineCustomerService: "অনলাইন গ্রাহক সেবা",
    depositAssistance: "জমার সহায়তা",
    depositInfo: "জমার তথ্য",

    globalWithdrawal: "গ্লোবাল ফান্ড উত্তোলন",
    availableUSDT: "উপলব্ধ USDT ব্যালেন্স",
    paymentMethod: "আন্তর্জাতিক পেমেন্ট পদ্ধতি",
    selectPayout: "পেআউট সিস্টেম নির্বাচন করুন",
    enterAmount: "আপনার পরিমাণ লিখুন",
    confirmWithdrawal: "উত্তোলন নিশ্চিত করুন",
    payoutGateway: "পেআউট গেটওয়ে নির্বাচন করুন",
    bankWire: "আন্তর্জাতিক ব্যাংক ওয়্যার ট্রান্সফার",
    cryptoWallet: "ক্রিপ্টো নেটওয়ার্ক ওয়ালেট",
    enterMobile: "মোবাইল নম্বর / ওয়ালেট আইডি লিখুন",
    cryptoAddress: "আপনার নেটওয়ার্ক ওয়ালেট ঠিকানা পেস্ট করুন",
    securityPassword: "নিরাপত্তা পাসওয়ার্ড লিখুন",

    transferTitle: "ট্রান্সফার",
    transferFunds: "তহবিল স্থানান্তর",
    fromAccount: "উৎস অ্যাকাউন্ট",
    toAccount: "গন্তব্য অ্যাকাউন্ট",
    transferAmount: "স্থানান্তর পরিমাণ",
    confirm: "নিশ্চিত করুন",

    inviteTitle: "বন্ধু আমন্ত্রণ",
    myReferrals: "আমার রেফারেল",
    copyLink: "আমন্ত্রণ লিংক কপি করুন",
    shareCode: "কোড শেয়ার করুন",
    totalReferrals: "মোট রেফারেল",

    accountHelp: "অ্যাকাউন্ট সহায়তা",
    manageProfile: "প্রোফাইল পরিচালনা",
    addFunds: "নিরাপদে অর্থ যোগ করুন",
    payoutRequests: "পেআউট অনুরোধ",
    generalSupport: "সাধারণ সাপোর্ট",

    wealthTitle: "ওয়েলথ",
    noSubscriptions: "কোনো সাবস্ক্রিপশন নেই",
    dailyIncome: "দৈনিক আয়",
    duration: "মেয়াদ",
    minimum: "সর্বনিম্ন",
    subscribe: "সাবস্ক্রাইব",
    days: "দিন",

    copySquare: "কপি স্কোয়ার",
    professional: "প্রফেশনাল",
    amateur: "অ্যামেচার",
    myMaster: "আমার মাস্টার",
    profitRate: "মুনাফার হার",

    settingsTitle: "সেটিংস",
    changePassword: "পাসওয়ার্ড ও নিরাপত্তা পরিবর্তন",
    language: "ভাষা",
    darkMode: "ডার্ক মোড",
    appVersion: "অ্যাপ ভার্সন",
    latest: "সর্বশেষ",

    loanTitle: "ঋণ",
    applyLoan: "ঋণের জন্য আবেদন",
    loanAmount: "ঋণের পরিমাণ",
    repayment: "পরিশোধ",
    interestRate: "সুদের হার",

    ordersTitle: "আমার অর্ডার",
    noOrders: "কোনো অর্ডার পাওয়া যায়নি",
    profit: "লাভ",
    loss: "লোকসান",
    status: "অবস্থা",
    symbol: "সিম্বল",
    orderType: "অর্ডারের ধরন",

    loading: "লোড হচ্ছে...",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    submit: "জমা দিন",
    ok: "ঠিক আছে",
    back: "পিছনে",
    next: "পরবর্তী",
    globalPlatform: "গ্লোবাল ইন্টিগ্রেটেড ফিনান্সিয়াল ট্রেডিং প্ল্যাটফর্ম",
  },

  // ─────────────────────────────────────────
  // 3. हिन्दी 🇮🇳
  // ─────────────────────────────────────────
  hi_IN: {
    flag: "🇮🇳",
    langName: "हिन्दी",

    username: "यूजरनेम",
    password: "पासवर्ड",
    signin: "साइन इन करें",
    createAccount: "खाता बनाएं",
    forgotPassword: "पासवर्ड भूल गए?",

    regTitle: "खाता बनाएं",
    regSubtitle: "वैश्विक ट्रेडिंग के लिए CptMarkets से जुड़ें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    inviteCode: "आमंत्रण कोड (वैकल्पिक)",
    register: "पंजीकरण करें",
    alreadyAccount: "पहले से खाता है?",
    signIn: "साइन इन",

    navHome: "होम",
    navMarkets: "बाज़ार",
    navAssets: "संपत्ति",
    navMine: "प्रोफ़ाइल",
    navTrade: "ट्रेड",

    totalAssets: "कुल संपत्ति (USD)",
    floatingPL: "फ्लोटिंग लाभ/हानि",
    equity: "इक्विटी",
    deposit: "जमा",
    withdraw: "निकासी",
    transfer: "ट्रांसफर",
    support: "सहायता",
    copyTrade: "कॉपी ट्रेड",
    loan: "ऋण",
    wealth: "वेल्थ",
    mining: "माइनिंग",
    invite: "आमंत्रित करें",
    hotMarkets: "हॉट मार्केट",
    viewAll: "सब देखें",

    all: "सभी",
    forex: "फॉरेक्स",
    crypto: "क्रिप्टो",
    metals: "धातु",
    indices: "सूचकांक",
    notifications: "सूचनाएं",
    close: "बंद करें",

    assetsTitle: "संपत्ति",
    available: "उपलब्ध",
    frozen: "फ्रोज़न",
    fundingAccount: "फंडिंग खाता",
    mainWalletBalance: "मुख्य वॉलेट बैलेंस",
    spotAccount: "स्पॉट खाता",
    spotTradingAssets: "स्पॉट ट्रेडिंग संपत्ति",
    futuresAccount: "फ्यूचर्स खाता",
    futuresBalance: "फ्यूचर्स बैलेंस",
    myAssets: "मेरी संपत्ति",
    history: "इतिहास",
    noRecords: "कोई रिकॉर्ड नहीं",

    leverage: "लीवरेज",
    convertedLots: "परिवर्तित लॉट",
    contractValue: "अनुबंध मूल्य",
    entryPrice: "प्रवेश मूल्य",
    currentPrice: "वर्तमान मूल्य",
    amount: "राशि",
    buyUp: "खरीदें (अप)",
    sellDown: "बेचें (डाउन)",
    openOrders: "खुले ऑर्डर",
    orderHistory: "ऑर्डर इतिहास",

    todayPL: "आज का लाभ/हानि",
    totalPL: "कुल लाभ/हानि",
    open: "खुला",
    myOrders: "मेरे ऑर्डर",
    copyTrading: "कॉपी ट्रेडिंग",
    wealthMining: "वेल्थ / माइनिंग",
    inviteFriends: "दोस्तों को आमंत्रित करें",
    walletManagement: "वॉलेट प्रबंधन",
    security: "सुरक्षा",
    announcements: "घोषणाएं",
    signOut: "साइन आउट",
    loginPassword: "लॉगिन पासवर्ड",
    protectAccount: "एक सुरक्षित पासवर्ड से अपना खाता सुरक्षित रखें।",
    accountSecurity: "खाता सुरक्षा",
    keepAccountSafe: "अपनी खाता जानकारी सुरक्षित रखें।",
    securityVerification: "सुरक्षा सत्यापन",
    manageVerification: "अपने खाता सत्यापन सेटिंग्स प्रबंधित करें।",

    depositTitle: "जमा",
    fundAccount: "अपने CptMarkets खाते में फंड करें",
    depositGuidelines: "जमा दिशानिर्देश",
    startRequest: "अनुरोध शुरू करें",
    provideUID: "अपना खाता UID दें",
    confirmPayment: "भुगतान विवरण की पुष्टि करें",
    submitReceipt: "अपनी रसीद जमा करें",
    officialSupport: "आधिकारिक सहायता चैनल का उपयोग करें",
    onlineCustomerService: "ऑनलाइन ग्राहक सेवा",
    depositAssistance: "जमा सहायता",
    depositInfo: "जमा जानकारी",

    globalWithdrawal: "वैश्विक फंड निकासी",
    availableUSDT: "उपलब्ध USDT बैलेंस",
    paymentMethod: "अंतर्राष्ट्रीय भुगतान विधि",
    selectPayout: "पेआउट सिस्टम चुनें",
    enterAmount: "अपनी राशि दर्ज करें",
    confirmWithdrawal: "निकासी की पुष्टि करें",
    payoutGateway: "पेआउट गेटवे चुनें",
    bankWire: "अंतर्राष्ट्रीय बैंक वायर ट्रांसफर",
    cryptoWallet: "क्रिप्टो नेटवर्क वॉलेट",
    enterMobile: "मोबाइल नंबर / वॉलेट आईडी दर्ज करें",
    cryptoAddress: "अपना नेटवर्क वॉलेट पता पेस्ट करें",
    securityPassword: "सुरक्षा पासवर्ड दर्ज करें",

    transferTitle: "ट्रांसफर",
    transferFunds: "फंड ट्रांसफर",
    fromAccount: "स्रोत खाता",
    toAccount: "गंतव्य खाता",
    transferAmount: "ट्रांसफर राशि",
    confirm: "पुष्टि करें",

    inviteTitle: "दोस्तों को आमंत्रित करें",
    myReferrals: "मेरे रेफरल",
    copyLink: "आमंत्रण लिंक कॉपी करें",
    shareCode: "कोड शेयर करें",
    totalReferrals: "कुल रेफरल",

    accountHelp: "खाता सहायता",
    manageProfile: "प्रोफ़ाइल प्रबंधित करें",
    addFunds: "सुरक्षित रूप से फंड जोड़ें",
    payoutRequests: "पेआउट अनुरोध",
    generalSupport: "सामान्य सहायता",

    wealthTitle: "वेल्थ",
    noSubscriptions: "कोई सदस्यता नहीं",
    dailyIncome: "दैनिक आय",
    duration: "अवधि",
    minimum: "न्यूनतम",
    subscribe: "सदस्यता लें",
    days: "दिन",

    copySquare: "कॉपी स्क्वायर",
    professional: "प्रोफेशनल",
    amateur: "शौकिया",
    myMaster: "मेरा मास्टर",
    profitRate: "लाभ दर",

    settingsTitle: "सेटिंग्स",
    changePassword: "पासवर्ड और सुरक्षा विकल्प बदलें",
    language: "भाषा",
    darkMode: "डार्क मोड",
    appVersion: "ऐप वर्जन",
    latest: "नवीनतम",

    loanTitle: "ऋण",
    applyLoan: "ऋण के लिए आवेदन करें",
    loanAmount: "ऋण राशि",
    repayment: "पुनर्भुगतान",
    interestRate: "ब्याज दर",

    ordersTitle: "मेरे ऑर्डर",
    noOrders: "कोई ऑर्डर नहीं मिला",
    profit: "लाभ",
    loss: "हानि",
    status: "स्थिति",
    symbol: "सिम्बल",
    orderType: "ऑर्डर प्रकार",

    loading: "लोड हो रहा है...",
    save: "सहेजें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    ok: "ठीक है",
    back: "वापस",
    next: "अगला",
    globalPlatform: "वैश्विक एकीकृत वित्तीय ट्रेडिंग प्लेटफॉर्म",
  },

  // ─────────────────────────────────────────
  // 4. English (US) 🇺🇸
  // ─────────────────────────────────────────
  en_US: {
    flag: "🇺🇸",
    langName: "English (US)",

    username: "Username",
    password: "Password",
    signin: "Sign In",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",

    regTitle: "Create Account",
    regSubtitle: "Join CptMarkets for global trading",
    confirmPassword: "Confirm Password",
    inviteCode: "Invite Code (optional)",
    register: "Register",
    alreadyAccount: "Already have an account?",
    signIn: "Sign In",

    navHome: "Home",
    navMarkets: "Markets",
    navAssets: "Assets",
    navMine: "Profile",
    navTrade: "Trade",

    totalAssets: "Total Assets (USD)",
    floatingPL: "Floating P/L",
    equity: "Equity",
    deposit: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    support: "Support",
    copyTrade: "Copy Trade",
    loan: "Loan",
    wealth: "Wealth",
    mining: "Mining",
    invite: "Invite",
    hotMarkets: "Hot Markets",
    viewAll: "View All",

    all: "All",
    forex: "Forex",
    crypto: "Crypto",
    metals: "Metals",
    indices: "Indices",
    notifications: "Notifications",
    close: "Close",

    assetsTitle: "Assets",
    available: "Available",
    frozen: "Frozen",
    fundingAccount: "Funding Account",
    mainWalletBalance: "Main Wallet Balance",
    spotAccount: "Spot Account",
    spotTradingAssets: "Spot Trading Assets",
    futuresAccount: "Futures Account",
    futuresBalance: "Futures Balance",
    myAssets: "My Assets",
    history: "History",
    noRecords: "No records",

    leverage: "Leverage",
    convertedLots: "Converted Lots",
    contractValue: "Contract Value",
    entryPrice: "Entry Price",
    currentPrice: "Current Price",
    amount: "Amount",
    buyUp: "Buy Up",
    sellDown: "Sell Down",
    openOrders: "Open Orders",
    orderHistory: "Order History",

    todayPL: "Today P/L",
    totalPL: "Total P/L",
    open: "Open",
    myOrders: "My Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Wealth / Mining",
    inviteFriends: "Invite Friends",
    walletManagement: "Wallet Management",
    security: "Security",
    announcements: "Announcements",
    signOut: "Sign Out",
    loginPassword: "Login Password",
    protectAccount: "Protect your account with a secure password.",
    accountSecurity: "Account Security",
    keepAccountSafe: "Keep your account information safe.",
    securityVerification: "Security Verification",
    manageVerification: "Manage your account verification settings.",

    depositTitle: "Deposit",
    fundAccount: "Fund Your CptMarkets Account",
    depositGuidelines: "Deposit Guidelines",
    startRequest: "Start Your Request",
    provideUID: "Provide Your Account UID",
    confirmPayment: "Confirm Payment Details",
    submitReceipt: "Submit Your Receipt",
    officialSupport: "Use the Official Support Channel",
    onlineCustomerService: "Online Customer Service",
    depositAssistance: "Deposit Assistance",
    depositInfo: "Deposit Information",

    globalWithdrawal: "Global Fund Withdrawal",
    availableUSDT: "Available USDT Balance",
    paymentMethod: "International Payment Method",
    selectPayout: "Select payout system",
    enterAmount: "Enter your amount",
    confirmWithdrawal: "Confirm Withdrawal",
    payoutGateway: "Select Payout Gateway",
    bankWire: "International Bank Wire Transfer",
    cryptoWallet: "Crypto Network Exchange Wallet",
    enterMobile: "Enter Mobile Number / Wallet ID",
    cryptoAddress: "Paste your network wallet address",
    securityPassword: "Enter security password",

    transferTitle: "Transfer",
    transferFunds: "Transfer Funds",
    fromAccount: "From Account",
    toAccount: "To Account",
    transferAmount: "Transfer Amount",
    confirm: "Confirm",

    inviteTitle: "Invite Friends",
    myReferrals: "My Referrals",
    copyLink: "Copy Invite Link",
    shareCode: "Share Code",
    totalReferrals: "Total Referrals",

    accountHelp: "Account Help",
    manageProfile: "Manage profile",
    addFunds: "Add funds safely",
    payoutRequests: "Payout requests",
    generalSupport: "General Support",

    wealthTitle: "Wealth",
    noSubscriptions: "No subscriptions",
    dailyIncome: "Daily Income",
    duration: "Duration",
    minimum: "Minimum",
    subscribe: "Subscribe",
    days: "Days",

    copySquare: "Copy Square",
    professional: "Professional",
    amateur: "Amateur",
    myMaster: "My Master",
    profitRate: "Profit Rate",

    settingsTitle: "Settings",
    changePassword: "Change password and security options",
    language: "Language",
    darkMode: "Dark Mode",
    appVersion: "App Version",
    latest: "Latest",

    loanTitle: "Loan",
    applyLoan: "Apply for Loan",
    loanAmount: "Loan Amount",
    repayment: "Repayment",
    interestRate: "Interest Rate",

    ordersTitle: "My Orders",
    noOrders: "No orders found",
    profit: "Profit",
    loss: "Loss",
    status: "Status",
    symbol: "Symbol",
    orderType: "Order Type",

    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    ok: "OK",
    back: "Back",
    next: "Next",
    globalPlatform: "Global integrated financial trading platform",
  },
    // ─────────────────────────────────────────
  // 7. Deutsch 🇩🇪
  // ─────────────────────────────────────────
  de_DE: {
    flag: "🇩🇪",
    langName: "Deutsch",

    username: "Benutzername",
    password: "Passwort",
    signin: "Anmelden",
    createAccount: "Konto erstellen",
    forgotPassword: "Passwort vergessen?",

    regTitle: "Konto erstellen",
    regSubtitle: "Treten Sie CptMarkets für globales Trading bei",
    confirmPassword: "Passwort bestätigen",
    inviteCode: "Einladungscode (optional)",
    register: "Registrieren",
    alreadyAccount: "Sie haben bereits ein Konto?",
    signIn: "Anmelden",

    navHome: "Startseite",
    navMarkets: "Märkte",
    navAssets: "Vermögenswerte",
    navMine: "Profil",
    navTrade: "Trading",

    totalAssets: "Gesamtvermögen (USD)",
    floatingPL: "Offener Gewinn/Verlust",
    equity: "Eigenkapital",
    deposit: "Einzahlen",
    withdraw: "Auszahlen",
    transfer: "Überweisen",
    support: "Support",
    copyTrade: "Copy Trading",
    loan: "Kredit",
    wealth: "Vermögen",
    mining: "Mining",
    invite: "Einladen",
    hotMarkets: "Top-Märkte",
    viewAll: "Alle anzeigen",

    all: "Alle",
    forex: "Forex",
    crypto: "Krypto",
    metals: "Metalle",
    indices: "Indizes",
    notifications: "Benachrichtigungen",
    close: "Schließen",

    assetsTitle: "Vermögenswerte",
    available: "Verfügbar",
    frozen: "Eingefroren",
    fundingAccount: "Finanzierungskonto",
    mainWalletBalance: "Haupt-Wallet-Guthaben",
    spotAccount: "Spot-Konto",
    spotTradingAssets: "Spot-Handelsvermögen",
    futuresAccount: "Futures-Konto",
    futuresBalance: "Futures-Guthaben",
    myAssets: "Meine Vermögenswerte",
    history: "Verlauf",
    noRecords: "Keine Einträge",

    leverage: "Hebel",
    convertedLots: "Umgewandelte Lots",
    contractValue: "Kontraktwert",
    entryPrice: "Einstiegspreis",
    currentPrice: "Aktueller Preis",
    amount: "Betrag",
    buyUp: "Kaufen (Steigend)",
    sellDown: "Verkaufen (Fallend)",
    openOrders: "Offene Orders",
    orderHistory: "Orderverlauf",

    todayPL: "Gewinn/Verlust heute",
    totalPL: "Gesamtgewinn/-verlust",
    open: "Offen",
    myOrders: "Meine Orders",
    copyTrading: "Copy Trading",
    wealthMining: "Vermögen / Mining",
    inviteFriends: "Freunde einladen",
    walletManagement: "Wallet-Verwaltung",
    security: "Sicherheit",
    announcements: "Ankündigungen",
    signOut: "Abmelden",
    loginPassword: "Login-Passwort",
    protectAccount: "Schützen Sie Ihr Konto mit einem sicheren Passwort.",
    accountSecurity: "Kontosicherheit",
    keepAccountSafe: "Bewahren Sie Ihre Kontoinformationen sicher auf.",
    securityVerification: "Sicherheitsüberprüfung",
    manageVerification: "Verwalten Sie Ihre Kontoverifizierung.",

    depositTitle: "Einzahlung",
    fundAccount: "CptMarkets-Konto aufladen",
    depositGuidelines: "Einzahlungsrichtlinien",
    startRequest: "Anfrage starten",
    provideUID: "Geben Sie Ihre Konto-UID an",
    confirmPayment: "Zahlungsdetails bestätigen",
    submitReceipt: "Beleg einreichen",
    officialSupport: "Offiziellen Support-Kanal verwenden",
    onlineCustomerService: "Online-Kundenservice",
    depositAssistance: "Einzahlungsunterstützung",
    depositInfo: "Einzahlungsinformationen",

    globalWithdrawal: "Globale Auszahlung",
    availableUSDT: "Verfügbares USDT-Guthaben",
    paymentMethod: "Internationale Zahlungsmethode",
    selectPayout: "Zahlungssystem auswählen",
    enterAmount: "Betrag eingeben",
    confirmWithdrawal: "Auszahlung bestätigen",
    payoutGateway: "Zahlungsgateway auswählen",
    bankWire: "Internationale Banküberweisung",
    cryptoWallet: "Krypto-Netzwerk-Wallet",
    enterMobile: "Handynummer / Wallet-ID eingeben",
    cryptoAddress: "Netzwerk-Wallet-Adresse einfügen",
    securityPassword: "Sicherheitspasswort eingeben",

    transferTitle: "Überweisung",
    transferFunds: "Geld überweisen",
    fromAccount: "Von Konto",
    toAccount: "Auf Konto",
    transferAmount: "Überweisungsbetrag",
    confirm: "Bestätigen",

    inviteTitle: "Freunde einladen",
    myReferrals: "Meine Empfehlungen",
    copyLink: "Einladungslink kopieren",
    shareCode: "Code teilen",
    totalReferrals: "Empfehlungen insgesamt",

    accountHelp: "Kontohilfe",
    manageProfile: "Profil verwalten",
    addFunds: "Sicher Geld hinzufügen",
    payoutRequests: "Auszahlungsanfragen",
    generalSupport: "Allgemeiner Support",

    wealthTitle: "Vermögen",
    noSubscriptions: "Keine Abonnements",
    dailyIncome: "Tägliches Einkommen",
    duration: "Laufzeit",
    minimum: "Minimum",
    subscribe: "Abonnieren",
    days: "Tage",

    copySquare: "Copy Square",
    professional: "Profi",
    amateur: "Amateur",
    myMaster: "Mein Master",
    profitRate: "Gewinnrate",

    settingsTitle: "Einstellungen",
    changePassword: "Passwort und Sicherheitseinstellungen ändern",
    language: "Sprache",
    darkMode: "Dunkelmodus",
    appVersion: "App-Version",
    latest: "Neueste",

    loanTitle: "Kredit",
    applyLoan: "Kredit beantragen",
    loanAmount: "Kreditbetrag",
    repayment: "Rückzahlung",
    interestRate: "Zinssatz",

    ordersTitle: "Meine Orders",
    noOrders: "Keine Orders gefunden",
    profit: "Gewinn",
    loss: "Verlust",
    status: "Status",
    symbol: "Symbol",
    orderType: "Ordertyp",

    loading: "Wird geladen...",
    save: "Speichern",
    cancel: "Abbrechen",
    submit: "Absenden",
    ok: "OK",
    back: "Zurück",
    next: "Weiter",
    globalPlatform: "Globale integrierte Finanzhandelsplattform",
  },

  // ─────────────────────────────────────────
  // 8. 中文（简体）🇨🇳
  // ─────────────────────────────────────────
  zh_CN: {
    flag: "🇨🇳",
    langName: "简体中文",

    username: "用户名",
    password: "密码",
    signin: "登录",
    createAccount: "创建账户",
    forgotPassword: "忘记密码？",

    regTitle: "创建账户",
    regSubtitle: "加入 CptMarkets，开启全球交易",
    confirmPassword: "确认密码",
    inviteCode: "邀请码（可选）",
    register: "注册",
    alreadyAccount: "已经有账户？",
    signIn: "登录",

    navHome: "首页",
    navMarkets: "市场",
    navAssets: "资产",
    navMine: "我的",
    navTrade: "交易",

    totalAssets: "总资产（USD）",
    floatingPL: "浮动盈亏",
    equity: "净值",
    deposit: "充值",
    withdraw: "提现",
    transfer: "转账",
    support: "客服",
    copyTrade: "跟单交易",
    loan: "贷款",
    wealth: "财富",
    mining: "挖矿",
    invite: "邀请",
    hotMarkets: "热门市场",
    viewAll: "查看全部",

    all: "全部",
    forex: "外汇",
    crypto: "加密货币",
    metals: "贵金属",
    indices: "指数",
    notifications: "通知",
    close: "关闭",

    assetsTitle: "资产",
    available: "可用",
    frozen: "冻结",
    fundingAccount: "资金账户",
    mainWalletBalance: "主钱包余额",
    spotAccount: "现货账户",
    spotTradingAssets: "现货交易资产",
    futuresAccount: "期货账户",
    futuresBalance: "期货余额",
    myAssets: "我的资产",
    history: "历史记录",
    noRecords: "暂无记录",

    leverage: "杠杆",
    convertedLots: "换算手数",
    contractValue: "合约价值",
    entryPrice: "入场价格",
    currentPrice: "当前价格",
    amount: "金额",
    buyUp: "买涨",
    sellDown: "买跌",
    openOrders: "未平仓订单",
    orderHistory: "订单历史",

    todayPL: "今日盈亏",
    totalPL: "总盈亏",
    open: "打开",
    myOrders: "我的订单",
    copyTrading: "跟单交易",
    wealthMining: "财富 / 挖矿",
    inviteFriends: "邀请好友",
    walletManagement: "钱包管理",
    security: "安全",
    announcements: "公告",
    signOut: "退出登录",
    loginPassword: "登录密码",
    protectAccount: "使用安全密码保护您的账户。",
    accountSecurity: "账户安全",
    keepAccountSafe: "请妥善保护您的账户信息。",
    securityVerification: "安全验证",
    manageVerification: "管理您的账户验证设置。",

    depositTitle: "充值",
    fundAccount: "为您的 CptMarkets 账户充值",
    depositGuidelines: "充值指南",
    startRequest: "开始申请",
    provideUID: "提供您的账户 UID",
    confirmPayment: "确认付款信息",
    submitReceipt: "提交付款凭证",
    officialSupport: "使用官方客服渠道",
    onlineCustomerService: "在线客服",
    depositAssistance: "充值帮助",
    depositInfo: "充值信息",

    globalWithdrawal: "全球资金提现",
    availableUSDT: "可用 USDT 余额",
    paymentMethod: "国际支付方式",
    selectPayout: "选择付款系统",
    enterAmount: "输入金额",
    confirmWithdrawal: "确认提现",
    payoutGateway: "选择付款网关",
    bankWire: "国际银行电汇",
    cryptoWallet: "加密货币网络钱包",
    enterMobile: "输入手机号码 / 钱包 ID",
    cryptoAddress: "粘贴网络钱包地址",
    securityPassword: "输入安全密码",

    transferTitle: "转账",
    transferFunds: "转移资金",
    fromAccount: "转出账户",
    toAccount: "转入账户",
    transferAmount: "转账金额",
    confirm: "确认",

    inviteTitle: "邀请好友",
    myReferrals: "我的推荐",
    copyLink: "复制邀请链接",
    shareCode: "分享代码",
    totalReferrals: "推荐总数",

    accountHelp: "账户帮助",
    manageProfile: "管理个人资料",
    addFunds: "安全添加资金",
    payoutRequests: "付款申请",
    generalSupport: "一般支持",

    wealthTitle: "财富",
    noSubscriptions: "暂无订阅",
    dailyIncome: "每日收益",
    duration: "期限",
    minimum: "最低金额",
    subscribe: "订阅",
    days: "天",

    copySquare: "跟单广场",
    professional: "专业交易员",
    amateur: "业余交易员",
    myMaster: "我的交易员",
    profitRate: "收益率",

    settingsTitle: "设置",
    changePassword: "修改密码和安全选项",
    language: "语言",
    darkMode: "深色模式",
    appVersion: "应用版本",
    latest: "最新",

    loanTitle: "贷款",
    applyLoan: "申请贷款",
    loanAmount: "贷款金额",
    repayment: "还款",
    interestRate: "利率",

    ordersTitle: "我的订单",
    noOrders: "未找到订单",
    profit: "盈利",
    loss: "亏损",
    status: "状态",
    symbol: "交易品种",
    orderType: "订单类型",

    loading: "加载中...",
    save: "保存",
    cancel: "取消",
    submit: "提交",
    ok: "确定",
    back: "返回",
    next: "下一步",
    globalPlatform: "全球一体化金融交易平台",
  },

  // ─────────────────────────────────────────
  // 9. 日本語 🇯🇵
  // ─────────────────────────────────────────
  ja_JP: {
    flag: "🇯🇵",
    langName: "日本語",

    username: "ユーザー名",
    password: "パスワード",
    signin: "サインイン",
    createAccount: "アカウント作成",
    forgotPassword: "パスワードをお忘れですか？",

    regTitle: "アカウントを作成",
    regSubtitle: "CptMarketsでグローバルトレードを始めましょう",
    confirmPassword: "パスワードを確認",
    inviteCode: "招待コード（任意）",
    register: "登録",
    alreadyAccount: "すでにアカウントをお持ちですか？",
    signIn: "サインイン",

    navHome: "ホーム",
    navMarkets: "マーケット",
    navAssets: "資産",
    navMine: "マイページ",
    navTrade: "取引",

    totalAssets: "総資産（USD）",
    floatingPL: "含み損益",
    equity: "純資産",
    deposit: "入金",
    withdraw: "出金",
    transfer: "振替",
    support: "サポート",
    copyTrade: "コピートレード",
    loan: "ローン",
    wealth: "ウェルス",
    mining: "マイニング",
    invite: "招待",
    hotMarkets: "注目マーケット",
    viewAll: "すべて表示",

    all: "すべて",
    forex: "外国為替",
    crypto: "暗号資産",
    metals: "貴金属",
    indices: "指数",
    notifications: "通知",
    close: "閉じる",

    assetsTitle: "資産",
    available: "利用可能",
    frozen: "凍結",
    fundingAccount: "資金口座",
    mainWalletBalance: "メインウォレット残高",
    spotAccount: "現物口座",
    spotTradingAssets: "現物取引資産",
    futuresAccount: "先物口座",
    futuresBalance: "先物残高",
    myAssets: "マイ資産",
    history: "履歴",
    noRecords: "記録がありません",

    leverage: "レバレッジ",
    convertedLots: "換算ロット",
    contractValue: "契約価値",
    entryPrice: "エントリー価格",
    currentPrice: "現在価格",
    amount: "金額",
    buyUp: "買い（上昇）",
    sellDown: "売り（下降）",
    openOrders: "未決済注文",
    orderHistory: "注文履歴",

    todayPL: "本日の損益",
    totalPL: "総損益",
    open: "オープン",
    myOrders: "マイ注文",
    copyTrading: "コピートレード",
    wealthMining: "ウェルス / マイニング",
    inviteFriends: "友達を招待",
    walletManagement: "ウォレット管理",
    security: "セキュリティ",
    announcements: "お知らせ",
    signOut: "ログアウト",
    loginPassword: "ログインパスワード",
    protectAccount: "安全なパスワードでアカウントを保護してください。",
    accountSecurity: "アカウントセキュリティ",
    keepAccountSafe: "アカウント情報を安全に管理してください。",
    securityVerification: "セキュリティ認証",
    manageVerification: "アカウント認証設定を管理します。",

    depositTitle: "入金",
    fundAccount: "CptMarketsアカウントに入金",
    depositGuidelines: "入金ガイド",
    startRequest: "申請を開始",
    provideUID: "アカウントUIDを入力",
    confirmPayment: "支払い情報を確認",
    submitReceipt: "領収書を提出",
    officialSupport: "公式サポートチャンネルを利用",
    onlineCustomerService: "オンラインカスタマーサービス",
    depositAssistance: "入金サポート",
    depositInfo: "入金情報",

    globalWithdrawal: "グローバル資金出金",
    availableUSDT: "利用可能なUSDT残高",
    paymentMethod: "国際決済方法",
    selectPayout: "支払いシステムを選択",
    enterAmount: "金額を入力",
    confirmWithdrawal: "出金を確認",
    payoutGateway: "支払いゲートウェイを選択",
    bankWire: "国際銀行送金",
    cryptoWallet: "暗号資産ネットワークウォレット",
    enterMobile: "携帯番号 / ウォレットIDを入力",
    cryptoAddress: "ネットワークウォレットアドレスを貼り付け",
    securityPassword: "セキュリティパスワードを入力",

    transferTitle: "振替",
    transferFunds: "資金振替",
    fromAccount: "振替元口座",
    toAccount: "振替先口座",
    transferAmount: "振替金額",
    confirm: "確認",

    inviteTitle: "友達を招待",
    myReferrals: "紹介したユーザー",
    copyLink: "招待リンクをコピー",
    shareCode: "コードを共有",
    totalReferrals: "紹介総数",

    accountHelp: "アカウントヘルプ",
    manageProfile: "プロフィール管理",
    addFunds: "安全に資金を追加",
    payoutRequests: "支払い申請",
    generalSupport: "一般サポート",

    wealthTitle: "ウェルス",
    noSubscriptions: "購読はありません",
    dailyIncome: "日次収益",
    duration: "期間",
    minimum: "最低額",
    subscribe: "購読",
    days: "日",

    copySquare: "コピースクエア",
    professional: "プロフェッショナル",
    amateur: "アマチュア",
    myMaster: "マイマスター",
    profitRate: "利益率",

    settingsTitle: "設定",
    changePassword: "パスワードとセキュリティ設定を変更",
    language: "言語",
    darkMode: "ダークモード",
    appVersion: "アプリバージョン",
    latest: "最新",

    loanTitle: "ローン",
    applyLoan: "ローンを申請",
    loanAmount: "ローン金額",
    repayment: "返済",
    interestRate: "金利",

    ordersTitle: "マイ注文",
    noOrders: "注文が見つかりません",
    profit: "利益",
    loss: "損失",
    status: "ステータス",
    symbol: "銘柄",
    orderType: "注文タイプ",

    loading: "読み込み中...",
    save: "保存",
    cancel: "キャンセル",
    submit: "送信",
    ok: "OK",
    back: "戻る",
    next: "次へ",
    globalPlatform: "グローバル統合金融取引プラットフォーム",
  },
    // ─────────────────────────────────────────
  // 10. Italiano 🇮🇹
  // ─────────────────────────────────────────
  it_IT: {
    flag: "🇮🇹",
    langName: "Italiano",

    username: "Nome utente",
    password: "Password",
    signin: "Accedi",
    createAccount: "Crea account",
    forgotPassword: "Password dimenticata?",

    regTitle: "Crea account",
    regSubtitle: "Unisciti a CptMarkets per il trading globale",
    confirmPassword: "Conferma password",
    inviteCode: "Codice invito (opzionale)",
    register: "Registrati",
    alreadyAccount: "Hai già un account?",
    signIn: "Accedi",

    navHome: "Home",
    navMarkets: "Mercati",
    navAssets: "Asset",
    navMine: "Profilo",
    navTrade: "Trading",

    totalAssets: "Asset totali (USD)",
    floatingPL: "Profitto/Perdita fluttuante",
    equity: "Patrimonio",
    deposit: "Deposita",
    withdraw: "Preleva",
    transfer: "Trasferisci",
    support: "Supporto",
    copyTrade: "Copy Trading",
    loan: "Prestito",
    wealth: "Patrimonio",
    mining: "Mining",
    invite: "Invita",
    hotMarkets: "Mercati principali",
    viewAll: "Visualizza tutto",

    all: "Tutti",
    forex: "Forex",
    crypto: "Criptovalute",
    metals: "Metalli",
    indices: "Indici",
    notifications: "Notifiche",
    close: "Chiudi",

    assetsTitle: "Asset",
    available: "Disponibile",
    frozen: "Bloccato",
    fundingAccount: "Conto di finanziamento",
    mainWalletBalance: "Saldo del wallet principale",
    spotAccount: "Conto Spot",
    spotTradingAssets: "Asset di trading Spot",
    futuresAccount: "Conto Futures",
    futuresBalance: "Saldo Futures",
    myAssets: "I miei asset",
    history: "Cronologia",
    noRecords: "Nessun dato",

    leverage: "Leva",
    convertedLots: "Lotti convertiti",
    contractValue: "Valore del contratto",
    entryPrice: "Prezzo di entrata",
    currentPrice: "Prezzo attuale",
    amount: "Importo",
    buyUp: "Compra (Rialzo)",
    sellDown: "Vendi (Ribasso)",
    openOrders: "Ordini aperti",
    orderHistory: "Cronologia ordini",

    todayPL: "P/L di oggi",
    totalPL: "P/L totale",
    open: "Aperto",
    myOrders: "I miei ordini",
    copyTrading: "Copy Trading",
    wealthMining: "Patrimonio / Mining",
    inviteFriends: "Invita amici",
    walletManagement: "Gestione wallet",
    security: "Sicurezza",
    announcements: "Annunci",
    signOut: "Esci",
    loginPassword: "Password di accesso",
    protectAccount: "Proteggi il tuo account con una password sicura.",
    accountSecurity: "Sicurezza dell'account",
    keepAccountSafe: "Mantieni al sicuro le informazioni del tuo account.",
    securityVerification: "Verifica di sicurezza",
    manageVerification: "Gestisci le impostazioni di verifica del tuo account.",

    depositTitle: "Deposito",
    fundAccount: "Ricarica il tuo account CptMarkets",
    depositGuidelines: "Linee guida per il deposito",
    startRequest: "Inizia la richiesta",
    provideUID: "Inserisci il tuo UID account",
    confirmPayment: "Conferma i dettagli del pagamento",
    submitReceipt: "Invia la ricevuta",
    officialSupport: "Utilizza il canale di supporto ufficiale",
    onlineCustomerService: "Servizio clienti online",
    depositAssistance: "Assistenza per il deposito",
    depositInfo: "Informazioni sul deposito",

    globalWithdrawal: "Prelievo globale di fondi",
    availableUSDT: "Saldo USDT disponibile",
    paymentMethod: "Metodo di pagamento internazionale",
    selectPayout: "Seleziona il sistema di pagamento",
    enterAmount: "Inserisci l'importo",
    confirmWithdrawal: "Conferma il prelievo",
    payoutGateway: "Seleziona il gateway di pagamento",
    bankWire: "Bonifico bancario internazionale",
    cryptoWallet: "Wallet della rete crypto",
    enterMobile: "Inserisci numero mobile / ID wallet",
    cryptoAddress: "Incolla l'indirizzo del wallet",
    securityPassword: "Inserisci la password di sicurezza",

    transferTitle: "Trasferimento",
    transferFunds: "Trasferisci fondi",
    fromAccount: "Dal conto",
    toAccount: "Al conto",
    transferAmount: "Importo del trasferimento",
    confirm: "Conferma",

    inviteTitle: "Invita amici",
    myReferrals: "I miei referral",
    copyLink: "Copia link di invito",
    shareCode: "Condividi codice",
    totalReferrals: "Referral totali",

    accountHelp: "Aiuto account",
    manageProfile: "Gestisci profilo",
    addFunds: "Aggiungi fondi in sicurezza",
    payoutRequests: "Richieste di pagamento",
    generalSupport: "Supporto generale",

    wealthTitle: "Patrimonio",
    noSubscriptions: "Nessun abbonamento",
    dailyIncome: "Entrate giornaliere",
    duration: "Durata",
    minimum: "Minimo",
    subscribe: "Abbonati",
    days: "Giorni",

    copySquare: "Copy Square",
    professional: "Professionista",
    amateur: "Amatore",
    myMaster: "Il mio Master",
    profitRate: "Tasso di profitto",

    settingsTitle: "Impostazioni",
    changePassword: "Modifica password e opzioni di sicurezza",
    language: "Lingua",
    darkMode: "Modalità scura",
    appVersion: "Versione app",
    latest: "Ultima",

    loanTitle: "Prestito",
    applyLoan: "Richiedi un prestito",
    loanAmount: "Importo del prestito",
    repayment: "Rimborso",
    interestRate: "Tasso di interesse",

    ordersTitle: "I miei ordini",
    noOrders: "Nessun ordine trovato",
    profit: "Profitto",
    loss: "Perdita",
    status: "Stato",
    symbol: "Simbolo",
    orderType: "Tipo di ordine",

    loading: "Caricamento...",
    save: "Salva",
    cancel: "Annulla",
    submit: "Invia",
    ok: "OK",
    back: "Indietro",
    next: "Avanti",
    globalPlatform: "Piattaforma globale integrata per il trading finanziario",
  },


  // ─────────────────────────────────────────
  // 11. Português 🇵🇹
  // ─────────────────────────────────────────
  pt_PT: {
    flag: "🇵🇹",
    langName: "Português",

    username: "Nome de utilizador",
    password: "Palavra-passe",
    signin: "Iniciar sessão",
    createAccount: "Criar conta",
    forgotPassword: "Esqueceu-se da palavra-passe?",

    regTitle: "Criar conta",
    regSubtitle: "Junte-se à CptMarkets para negociação global",
    confirmPassword: "Confirmar palavra-passe",
    inviteCode: "Código de convite (opcional)",
    register: "Registar",
    alreadyAccount: "Já tem uma conta?",
    signIn: "Iniciar sessão",

    navHome: "Início",
    navMarkets: "Mercados",
    navAssets: "Ativos",
    navMine: "Perfil",
    navTrade: "Negociação",

    totalAssets: "Ativos totais (USD)",
    floatingPL: "Lucro/Perda flutuante",
    equity: "Património",
    deposit: "Depositar",
    withdraw: "Levantar",
    transfer: "Transferir",
    support: "Suporte",
    copyTrade: "Copy Trading",
    loan: "Empréstimo",
    wealth: "Património",
    mining: "Mineração",
    invite: "Convidar",
    hotMarkets: "Mercados em destaque",
    viewAll: "Ver tudo",

    all: "Todos",
    forex: "Forex",
    crypto: "Criptomoedas",
    metals: "Metais",
    indices: "Índices",
    notifications: "Notificações",
    close: "Fechar",

    assetsTitle: "Ativos",
    available: "Disponível",
    frozen: "Congelado",
    fundingAccount: "Conta de financiamento",
    mainWalletBalance: "Saldo da carteira principal",
    spotAccount: "Conta Spot",
    spotTradingAssets: "Ativos de negociação Spot",
    futuresAccount: "Conta de Futuros",
    futuresBalance: "Saldo de Futuros",
    myAssets: "Os meus ativos",
    history: "Histórico",
    noRecords: "Sem registos",

    leverage: "Alavancagem",
    convertedLots: "Lotes convertidos",
    contractValue: "Valor do contrato",
    entryPrice: "Preço de entrada",
    currentPrice: "Preço atual",
    amount: "Montante",
    buyUp: "Comprar (Alta)",
    sellDown: "Vender (Baixa)",
    openOrders: "Ordens abertas",
    orderHistory: "Histórico de ordens",

    todayPL: "P/L de hoje",
    totalPL: "P/L total",
    open: "Aberto",
    myOrders: "As minhas ordens",
    copyTrading: "Copy Trading",
    wealthMining: "Património / Mineração",
    inviteFriends: "Convidar amigos",
    walletManagement: "Gestão da carteira",
    security: "Segurança",
    announcements: "Anúncios",
    signOut: "Terminar sessão",
    loginPassword: "Palavra-passe de acesso",
    protectAccount: "Proteja a sua conta com uma palavra-passe segura.",
    accountSecurity: "Segurança da conta",
    keepAccountSafe: "Mantenha as informações da sua conta seguras.",
    securityVerification: "Verificação de segurança",
    manageVerification: "Gerir as definições de verificação da sua conta.",

    depositTitle: "Depósito",
    fundAccount: "Financie a sua conta CptMarkets",
    depositGuidelines: "Orientações para depósitos",
    startRequest: "Iniciar pedido",
    provideUID: "Indique o UID da sua conta",
    confirmPayment: "Confirmar dados de pagamento",
    submitReceipt: "Enviar recibo",
    officialSupport: "Utilizar o canal oficial de suporte",
    onlineCustomerService: "Serviço de atendimento online",
    depositAssistance: "Assistência de depósito",
    depositInfo: "Informações de depósito",

    globalWithdrawal: "Levantamento global de fundos",
    availableUSDT: "Saldo USDT disponível",
    paymentMethod: "Método de pagamento internacional",
    selectPayout: "Selecionar sistema de pagamento",
    enterAmount: "Introduzir montante",
    confirmWithdrawal: "Confirmar levantamento",
    payoutGateway: "Selecionar gateway de pagamento",
    bankWire: "Transferência bancária internacional",
    cryptoWallet: "Carteira de rede de criptomoedas",
    enterMobile: "Introduzir número de telemóvel / ID da carteira",
    cryptoAddress: "Colar endereço da carteira",
    securityPassword: "Introduzir palavra-passe de segurança",

    transferTitle: "Transferência",
    transferFunds: "Transferir fundos",
    fromAccount: "Da conta",
    toAccount: "Para a conta",
    transferAmount: "Montante da transferência",
    confirm: "Confirmar",

    inviteTitle: "Convidar amigos",
    myReferrals: "Os meus referidos",
    copyLink: "Copiar link de convite",
    shareCode: "Partilhar código",
    totalReferrals: "Total de referidos",

    accountHelp: "Ajuda da conta",
    manageProfile: "Gerir perfil",
    addFunds: "Adicionar fundos com segurança",
    payoutRequests: "Pedidos de pagamento",
    generalSupport: "Suporte geral",

    wealthTitle: "Património",
    noSubscriptions: "Sem subscrições",
    dailyIncome: "Rendimento diário",
    duration: "Duração",
    minimum: "Mínimo",
    subscribe: "Subscrever",
    days: "Dias",

    copySquare: "Copy Square",
    professional: "Profissional",
    amateur: "Amador",
    myMaster: "O meu Master",
    profitRate: "Taxa de lucro",

    settingsTitle: "Definições",
    changePassword: "Alterar palavra-passe e opções de segurança",
    language: "Idioma",
    darkMode: "Modo escuro",
    appVersion: "Versão da aplicação",
    latest: "Mais recente",

    loanTitle: "Empréstimo",
    applyLoan: "Solicitar empréstimo",
    loanAmount: "Montante do empréstimo",
    repayment: "Reembolso",
    interestRate: "Taxa de juro",

    ordersTitle: "As minhas ordens",
    noOrders: "Nenhuma ordem encontrada",
    profit: "Lucro",
    loss: "Perda",
    status: "Estado",
    symbol: "Símbolo",
    orderType: "Tipo de ordem",

    loading: "A carregar...",
    save: "Guardar",
    cancel: "Cancelar",
    submit: "Enviar",
    ok: "OK",
    back: "Voltar",
    next: "Seguinte",
    globalPlatform: "Plataforma financeira global integrada de negociação",
  }
};
