/* =========================================================
   CPTMARKETS - lang.js
   CENTRAL LANGUAGE CONFIGURATION
   Languages: English, Spanish, Chinese, Japanese,
              Bangla, Hindi, French, Urdu
   ========================================================= */

window.CPT_LANG = {
  storageKey: "cptmarkets_language",
  defaultLanguage: "en",

  languages: {
    en: { name: "English", native: "English", flag: "🇬🇧", api: "en" },
    es: { name: "Spanish", native: "Español", flag: "🇪🇸", api: "es" },
    zh: { name: "Chinese", native: "中文", flag: "🇨🇳", api: "zh-CN" },
    ja: { name: "Japanese", native: "日本語", flag: "🇯🇵", api: "ja" },
    bn: { name: "Bangla", native: "বাংলা", flag: "🇧🇩", api: "bn" },
    hi: { name: "Hindi", native: "हिन्दी", flag: "🇮🇳", api: "hi" },
    fr: { name: "French", native: "Français", flag: "🇫🇷", api: "fr" },
    ur: { name: "Urdu", native: "اردو", flag: "🇵🇰", api: "ur" }
  },

  /*
   * Local translations.
   * The English text is always the source text. Unknown/dynamic
   * text can be translated by translator.js' remote fallback.
   */
  translations: {
    es: {
      "Logout":"Cerrar sesión",
      "Admin Dashboard":"Panel de administración",
      "Welcome to the CptMarkets administrator panel.":"Bienvenido al panel de administración de CptMarkets.",
      "Total Users":"Usuarios totales",
      "Total Balance":"Saldo total",
      "Deposits":"Depósitos",
      "Withdrawals":"Retiros",
      "Management":"Gestión",
      "Users":"Usuarios",
      "Balances":"Saldos",
      "View and manage balances":"Ver y gestionar saldos",
      "Manage registered users":"Gestionar usuarios registrados",
      "Manage deposit requests":"Gestionar solicitudes de depósito",
      "Manage withdrawal requests":"Gestionar solicitudes de retiro",
      "Trades":"Operaciones",
      "View trading activity":"Ver actividad de trading",
      "Support":"Soporte",
      "Customer support":"Atención al cliente",
      "Assets":"Activos",
      "Total Assets (USD)":"Activos totales (USD)",
      "Available":"Disponible",
      "Frozen":"Congelado",
      "Funding Account":"Cuenta de fondos",
      "Main Wallet Balance":"Saldo de la billetera principal",
      "Spot Account":"Cuenta Spot",
      "Spot Trading Assets":"Activos de trading Spot",
      "Futures Account":"Cuenta de futuros",
      "Futures Balance":"Saldo de futuros",
      "Deposit":"Depósito",
      "Withdraw":"Retirar",
      "Transfer":"Transferir",
      "My Assets":"Mis activos",
      "History":"Historial",
      "No records":"Sin registros",
      "Home":"Inicio",
      "Markets":"Mercados",
      "Trade":"Operar",
      "Mine":"Mi cuenta",
      "Global integrated financial trading platform":"Plataforma financiera integrada de trading global",
      "Floating P/L":"P/L flotante",
      "Equity":"Patrimonio",
      "Copy Trade":"Copy Trading",
      "Loan":"Préstamo",
      "Wealth":"Patrimonio",
      "Mining":"Minería",
      "Invite":"Invitar",
      "Hot Markets":"Mercados destacados",
      "View All":"Ver todo",
      "Gold / USD":"Oro / USD",
      "Silver / USD":"Plata / USD",
      "Bitcoin / USD":"Bitcoin / USD",
      "Deposit Center":"Centro de depósitos",
      "Fund Your CptMarkets Account":"Financia tu cuenta de CptMarkets",
      "Deposit Guidelines":"Guía de depósito",
      "Start Your Request":"Inicia tu solicitud",
      "Provide Your Account UID":"Proporciona el UID de tu cuenta",
      "Confirm Payment Details":"Confirma los datos de pago",
      "Submit Your Receipt":"Envía tu comprobante",
      "Use the Official Support Channel":"Usa el canal oficial de soporte",
      "Online Customer Service":"Atención al cliente en línea",
      "Deposit Assistance":"Asistencia para depósitos",
      "Contact Customer Service":"Contactar con atención al cliente",
      "Deposit Information":"Información de depósito",
      "Copy Square":"Copy Square",
      "Trader":"Trader",
      "My Follows":"Mis seguidos",
      "No traders":"No hay traders",
      "Not following any trader":"No sigues a ningún trader",
      "Invite Friends":"Invitar amigos",
      "My Invite Code":"Mi código de invitación",
      "Copy Invite Link":"Copiar enlace de invitación",
      "Invitees":"Invitados",
      "Total Commission":"Comisión total",
      "My Referrals":"Mis referidos",
      "No referrals":"Sin referidos",
      "Invite code copied!":"¡Código de invitación copiado!",
      "Credit Limit (USD)":"Límite de crédito (USD)",
      "Daily Rate 0.050% · Max 90 days":"Tasa diaria 0,050 % · Máximo 90 días",
      "Loan quota not activated":"Cuota de préstamo no activada",
      "Please contact staff to approve and activate your quota":"Contacta con el personal para aprobar y activar tu cuota",
      "Loan Requirements & Conditions:":"Requisitos y condiciones del préstamo:",
      "Important Rule:":"Regla importante:",
      "All":"Todos",
      "Forex":"Forex",
      "Crypto":"Cripto",
      "Metals":"Metales",
      "Indices":"Índices",
      "Language":"Idioma",
      "English (UK)":"Inglés (Reino Unido)",
      "Dark Mode":"Modo oscuro",
      "Active (Professional Theme)":"Activo (tema profesional)",
      "App Version":"Versión de la aplicación",
      "Latest":"Última",
      "Account Security":"Seguridad de la cuenta",
      "Change password and security options":"Cambiar contraseña y opciones de seguridad",
      "Security Verification":"Verificación de seguridad",
      "Announcements":"Anuncios",
      "Welcome to CptMarkets":"Bienvenido a CptMarkets",
      "Platform Update":"Actualización de la plataforma",
      "Latest Update":"Última actualización",
      "Sign Out":"Cerrar sesión",
      "Security":"Seguridad",
      "Wallet Management":"Gestión de billetera",
      "Security settings will be available soon.":"La configuración de seguridad estará disponible pronto.",
      "No announcements.":"No hay anuncios.",
      "Live Active Chat & Support":"Chat y soporte activo en vivo",
      "Get Instant Support from Our Expert Team 👋":"Obtén soporte instantáneo de nuestro equipo de expertos 👋",
      "Account Help":"Ayuda de cuenta",
      "Manage profile":"Gestionar perfil",
      "Add funds safely":"Añadir fondos de forma segura",
      "Payout requests":"Solicitudes de pago",
      "General Support":"Soporte general",
      "24/7 assistance":"Asistencia 24/7",
      "Our Services & Features":"Nuestros servicios y funciones",
      "Username":"Nombre de usuario",
      "Password":"Contraseña",
      "Confirm Password":"Confirmar contraseña",
      "Invite Code":"Código de invitación",
      "Register":"Registrarse",
      "Already have an account?":"¿Ya tienes una cuenta?",
      "Sign In":"Iniciar sesión",
      "Create Account":"Crear cuenta",
      "Forgot Password?":"¿Olvidaste tu contraseña?",
      "Go to Sign In":"Ir a iniciar sesión",
      "Join CptMarkets for global trading":"Únete a CptMarkets para trading global",
      "Leverage":"Apalancamiento",
      "By Amount":"Por importe",
      "By Lots":"Por lotes",
      "Amount / Margin (USD)":"Importe / Margen (USD)",
      "TP Price":"Precio TP",
      "SL Price":"Precio SL",
      "Converted Lots":"Lotes convertidos",
      "Contract Value":"Valor del contrato",
      "Est. Margin":"Margen estimado",
      "Long":"Largo",
      "Short":"Corto",
      "Open Trade":"Abrir operación",
      "Close Trade":"Cerrar operación",
      "Entry Price":"Precio de entrada",
      "Current Price":"Precio actual",
      "Amount":"Importe",
      "Profit / Loss":"Ganancia / Pérdida",
      "Transfer Funds":"Transferir fondos",
      "Move funds between your accounts":"Mover fondos entre tus cuentas",
      "From":"Desde",
      "To":"A",
      "Trading Account":"Cuenta de trading",
      "Available Balance":"Saldo disponible",
      "Transfer Amount":"Importe de transferencia",
      "Confirm Transfer":"Confirmar transferencia",
      "Secure Transfer":"Transferencia segura",
      "Contact Support":"Contactar soporte",
      "Please Contact":"Por favor, contacta con",
      "Global Fund Withdrawal":"Retiro global de fondos",
      "Available USDT Balance":"Saldo USDT disponible",
      "International Payment Method":"Método de pago internacional",
      "Select payout system":"Selecciona el sistema de pago",
      "Withdrawal Amount (USDT)":"Importe de retiro (USDT)",
      "Bank Account & Routing/SWIFT Details":"Datos de cuenta bancaria y Routing/SWIFT",
      "Mobile Banking / Digital Wallet Account":"Cuenta de banca móvil / billetera digital",
      "Crypto Exchange / Wallet Address (TRC20)":"Exchange de criptomonedas / dirección de billetera (TRC20)",
      "Fund / Trading Password":"Contraseña de fondos / trading",
      "Confirm Withdrawal":"Confirmar retiro",
      "My Orders":"Mis órdenes",
      "Wealth Fund":"Fondo patrimonial",
      "Mining Power":"Potencia de minería",
      "My Subscriptions":"Mis suscripciones",
      "No subscriptions":"No hay suscripciones",
      "Subscribe":"Suscribirse",
      "Product":"Producto",
      "Product description":"Descripción del producto",
      "Daily Income":"Ingreso diario",
      "Duration":"Duración",
      "Minimum":"Mínimo",
      "Subscription Amount (USD)":"Importe de suscripción (USD)",
      "Confirm Subscription":"Confirmar suscripción",
      "Subscription successful":"Suscripción exitosa",
      "Signing Out...":"Cerrando sesión..."
          },

    /* =====================================================
       BANGLA
       ===================================================== */

    bn: {
      "Logout":"লগআউট",
      "Admin Dashboard":"অ্যাডমিন ড্যাশবোর্ড",
      "Welcome to the CptMarkets administrator panel.":"CptMarkets অ্যাডমিন প্যানেলে স্বাগতম।",
      "Total Users":"মোট ব্যবহারকারী",
      "Total Balance":"মোট ব্যালেন্স",
      "Deposits":"ডিপোজিট",
      "Withdrawals":"উইথড্রল",
      "Management":"ম্যানেজমেন্ট",
      "Users":"ব্যবহারকারী",
      "Balances":"ব্যালেন্স",
      "View and manage balances":"ব্যালেন্স দেখুন ও পরিচালনা করুন",
      "Manage registered users":"নিবন্ধিত ব্যবহারকারী পরিচালনা করুন",
      "Manage deposit requests":"ডিপোজিটের অনুরোধ পরিচালনা করুন",
      "Manage withdrawal requests":"উইথড্রল অনুরোধ পরিচালনা করুন",
      "Trades":"ট্রেড",
      "View trading activity":"ট্রেডিং কার্যক্রম দেখুন",
      "Support":"সাপোর্ট",
      "Customer support":"কাস্টমার সাপোর্ট",
      "Assets":"অ্যাসেট",
      "Total Assets (USD)":"মোট অ্যাসেট (USD)",
      "Available":"উপলভ্য",
      "Frozen":"ফ্রোজেন",
      "Funding Account":"ফান্ডিং অ্যাকাউন্ট",
      "Main Wallet Balance":"মূল ওয়ালেট ব্যালেন্স",
      "Spot Account":"স্পট অ্যাকাউন্ট",
      "Spot Trading Assets":"স্পট ট্রেডিং অ্যাসেট",
      "Futures Account":"ফিউচার্স অ্যাকাউন্ট",
      "Futures Balance":"ফিউচার্স ব্যালেন্স",
      "Deposit":"ডিপোজিট",
      "Withdraw":"উইথড্রল",
      "Transfer":"ট্রান্সফার",
      "My Assets":"আমার অ্যাসেট",
      "History":"ইতিহাস",
      "No records":"কোনো রেকর্ড নেই",
      "Home":"হোম",
      "Markets":"মার্কেট",
      "Trade":"ট্রেড",
      "Mine":"আমার অ্যাকাউন্ট",
      "Global integrated financial trading platform":"গ্লোবাল ইন্টিগ্রেটেড ফাইন্যান্সিয়াল ট্রেডিং প্ল্যাটফর্ম",
      "Floating P/L":"ফ্লোটিং P/L",
      "Equity":"ইকুইটি",
      "Copy Trade":"কপি ট্রেড",
      "Loan":"লোন",
      "Wealth":"ওয়েলথ",
      "Mining":"মাইনিং",
      "Invite":"ইনভাইট",
      "Hot Markets":"জনপ্রিয় মার্কেট",
      "View All":"সব দেখুন",
      "Gold / USD":"গোল্ড / USD",
      "Silver / USD":"সিলভার / USD",
      "Bitcoin / USD":"বিটকয়েন / USD",
      "Deposit Center":"ডিপোজিট সেন্টার",
      "Fund Your CptMarkets Account":"আপনার CptMarkets অ্যাকাউন্টে ফান্ড যোগ করুন",
      "Deposit Guidelines":"ডিপোজিট নির্দেশিকা",
      "Start Your Request":"আপনার অনুরোধ শুরু করুন",
      "Provide Your Account UID":"আপনার অ্যাকাউন্ট UID দিন",
      "Confirm Payment Details":"পেমেন্টের তথ্য নিশ্চিত করুন",
      "Submit Your Receipt":"আপনার রসিদ জমা দিন",
      "Use the Official Support Channel":"অফিশিয়াল সাপোর্ট চ্যানেল ব্যবহার করুন",
      "Online Customer Service":"অনলাইন কাস্টমার সার্ভিস",
      "Deposit Assistance":"ডিপোজিট সহায়তা",
      "Contact Customer Service":"কাস্টমার সার্ভিসে যোগাযোগ করুন",
      "Deposit Information":"ডিপোজিট তথ্য",
      "Copy Square":"কপি স্কয়ার",
      "Trader":"ট্রেডার",
      "My Follows":"আমার ফলো",
      "No traders":"কোনো ট্রেডার নেই",
      "Not following any trader":"কোনো ট্রেডারকে ফলো করছেন না",
      "Invite Friends":"বন্ধুদের আমন্ত্রণ করুন",
      "My Invite Code":"আমার ইনভাইট কোড",
      "Copy Invite Link":"ইনভাইট লিংক কপি করুন",
      "Invitees":"আমন্ত্রিতরা",
      "Total Commission":"মোট কমিশন",
      "My Referrals":"আমার রেফারেল",
      "No referrals":"কোনো রেফারেল নেই",
      "Invite code copied!":"ইনভাইট কোড কপি হয়েছে!",
      "Credit Limit (USD)":"ক্রেডিট লিমিট (USD)",
      "Daily Rate 0.050% · Max 90 days":"দৈনিক হার 0.050% · সর্বোচ্চ ৯০ দিন",
      "Loan quota not activated":"লোন কোটা সক্রিয় নয়",
      "Please contact staff to approve and activate your quota":"কোটা অনুমোদন ও সক্রিয় করতে স্টাফের সাথে যোগাযোগ করুন",
      "Loan Requirements & Conditions:":"লোনের শর্ত ও প্রয়োজনীয়তা:",
      "Important Rule:":"গুরুত্বপূর্ণ নিয়ম:",
      "All":"সব",
      "Forex":"ফরেক্স",
      "Crypto":"ক্রিপ্টো",
      "Metals":"মেটাল",
      "Indices":"ইনডেক্স",
      "Language":"ভাষা",
      "English (UK)":"ইংরেজি (UK)",
      "Dark Mode":"ডার্ক মোড",
      "Active (Professional Theme)":"সক্রিয় (প্রফেশনাল থিম)",
      "App Version":"অ্যাপ ভার্সন",
      "Latest":"সর্বশেষ",
      "Account Security":"অ্যাকাউন্ট নিরাপত্তা",
      "Change password and security options":"পাসওয়ার্ড ও নিরাপত্তা অপশন পরিবর্তন করুন",
      "Security Verification":"নিরাপত্তা যাচাই",
      "Announcements":"ঘোষণা",
      "Welcome to CptMarkets":"CptMarkets-এ স্বাগতম",
      "Platform Update":"প্ল্যাটফর্ম আপডেট",
      "Latest Update":"সর্বশেষ আপডেট",
      "Sign Out":"সাইন আউট",
      "Security":"নিরাপত্তা",
      "Wallet Management":"ওয়ালেট ম্যানেজমেন্ট",
      "Security settings will be available soon.":"নিরাপত্তা সেটিংস শিগগিরই পাওয়া যাবে।",
      "No announcements.":"কোনো ঘোষণা নেই।",
      "Live Active Chat & Support":"লাইভ সক্রিয় চ্যাট ও সাপোর্ট",
      "Get Instant Support from Our Expert Team 👋":"আমাদের বিশেষজ্ঞ টিমের কাছ থেকে তাৎক্ষণিক সাপোর্ট নিন 👋",
      "Account Help":"অ্যাকাউন্ট সহায়তা",
      "Manage profile":"প্রোফাইল পরিচালনা",
      "Add funds safely":"নিরাপদে ফান্ড যোগ করুন",
      "Payout requests":"পেমেন্ট অনুরোধ",
      "General Support":"সাধারণ সাপোর্ট",
      "24/7 assistance":"২৪/৭ সহায়তা",
      "Our Services & Features":"আমাদের সেবা ও ফিচার",
      "Username":"ইউজারনেম",
      "Password":"পাসওয়ার্ড",
      "Confirm Password":"পাসওয়ার্ড নিশ্চিত করুন",
      "Invite Code":"ইনভাইট কোড",
      "Register":"রেজিস্টার",
      "Already have an account?":"আগেই অ্যাকাউন্ট আছে?",
      "Sign In":"সাইন ইন",
      "Create Account":"অ্যাকাউন্ট তৈরি করুন",
      "Forgot Password?":"পাসওয়ার্ড ভুলে গেছেন?",
      "Go to Sign In":"সাইন ইন-এ যান",
      "Join CptMarkets for global trading":"গ্লোবাল ট্রেডিংয়ের জন্য CptMarkets-এ যোগ দিন",
      "Leverage":"লিভারেজ",
      "By Amount":"অ্যামাউন্ট অনুযায়ী",
      "By Lots":"লট অনুযায়ী",
      "Amount / Margin (USD)":"অ্যামাউন্ট / মার্জিন (USD)",
      "TP Price":"TP মূল্য",
      "SL Price":"SL মূল্য",
      "Converted Lots":"কনভার্টেড লট",
      "Contract Value":"কন্ট্রাক্ট ভ্যালু",
      "Est. Margin":"আনুমানিক মার্জিন",
      "Long":"লং",
      "Short":"শর্ট",
      "Open Trade":"ট্রেড খুলুন",
      "Close Trade":"ট্রেড বন্ধ করুন",
      "Entry Price":"এন্ট্রি মূল্য",
      "Current Price":"বর্তমান মূল্য",
      "Amount":"অ্যামাউন্ট",
      "Profit / Loss":"লাভ / ক্ষতি",
      "Transfer Funds":"ফান্ড ট্রান্সফার",
      "Move funds between your accounts":"আপনার অ্যাকাউন্টগুলোর মধ্যে ফান্ড স্থানান্তর করুন",
      "From":"থেকে",
      "To":"প্রতি",
      "Trading Account":"ট্রেডিং অ্যাকাউন্ট",
      "Available Balance":"উপলভ্য ব্যালেন্স",
      "Transfer Amount":"ট্রান্সফার অ্যামাউন্ট",
      "Confirm Transfer":"ট্রান্সফার নিশ্চিত করুন",
      "Secure Transfer":"নিরাপদ ট্রান্সফার",
      "Contact Support":"সাপোর্টে যোগাযোগ করুন",
      "Please Contact":"যোগাযোগ করুন",
      "Global Fund Withdrawal":"গ্লোবাল ফান্ড উইথড্রল",
      "Available USDT Balance":"উপলভ্য USDT ব্যালেন্স",
      "International Payment Method":"আন্তর্জাতিক পেমেন্ট পদ্ধতি",
      "Select payout system":"পেমেন্ট সিস্টেম নির্বাচন করুন",
      "Withdrawal Amount (USDT)":"উইথড্রল অ্যামাউন্ট (USDT)",
      "Bank Account & Routing/SWIFT Details":"ব্যাংক অ্যাকাউন্ট ও Routing/SWIFT তথ্য",
      "Mobile Banking / Digital Wallet Account":"মোবাইল ব্যাংকিং / ডিজিটাল ওয়ালেট অ্যাকাউন্ট",
      "Crypto Exchange / Wallet Address (TRC20)":"ক্রিপ্টো এক্সচেঞ্জ / ওয়ালেট ঠিকানা (TRC20)",
      "Fund / Trading Password":"ফান্ড / ট্রেডিং পাসওয়ার্ড",
      "Confirm Withdrawal":"উইথড্রল নিশ্চিত করুন",
      "My Orders":"আমার অর্ডার",
      "Wealth Fund":"ওয়েলথ ফান্ড",
      "Mining Power":"মাইনিং পাওয়ার",
      "My Subscriptions":"আমার সাবস্ক্রিপশন",
      "No subscriptions":"কোনো সাবস্ক্রিপশন নেই",
      "Subscribe":"সাবস্ক্রাইব",
      "Product":"প্রোডাক্ট",
      "Product description":"প্রোডাক্টের বিবরণ",
      "Daily Income":"দৈনিক আয়",
      "Duration":"সময়কাল",
      "Minimum":"সর্বনিম্ন",
      "Subscription Amount (USD)":"সাবস্ক্রিপশন অ্যামাউন্ট (USD)",
      "Confirm Subscription":"সাবস্ক্রিপশন নিশ্চিত করুন",
      "Subscription successful":"সাবস্ক্রিপশন সফল হয়েছে",
      "Signing Out...":"সাইন আউট হচ্ছে..."
    }
  },

  /* =====================================================
     ADDITIONAL CORE TRANSLATIONS
     ===================================================== */

  wordTranslations: {

    zh: {
      "Logout":"退出登录",
      "Users":"用户",
      "Balances":"余额",
      "Deposits":"存款",
      "Withdrawals":"提现",
      "Support":"客服",
      "Assets":"资产",
      "Available":"可用",
      "Frozen":"冻结",
      "Deposit":"充值",
      "Withdraw":"提现",
      "Transfer":"转账",
      "History":"历史",
      "Home":"首页",
      "Markets":"市场",
      "Trade":"交易",
      "Language":"语言",
      "Username":"用户名",
      "Password":"密码",
      "Register":"注册",
      "Sign In":"登录",
      "Create Account":"创建账户",
      "Forgot Password?":"忘记密码？",
      "Leverage":"杠杆",
      "Long":"做多",
      "Short":"做空",
      "Open Trade":"开仓",
      "Close Trade":"平仓",
      "Amount":"金额",
      "Profit / Loss":"盈亏",
      "All":"全部",
      "Forex":"外汇",
      "Crypto":"加密货币",
      "Metals":"贵金属",
      "Indices":"指数",
      "Security":"安全",
      "Announcements":"公告",
      "Latest Update":"最新更新",
      "My Orders":"我的订单",
      "Subscribe":"订阅",
      "Product":"产品",
      "Daily Income":"每日收入",
      "Duration":"期限",
      "Minimum":"最低金额",
      "Confirm Withdrawal":"确认提现",
      "Confirm Transfer":"确认转账",
      "Contact Support":"联系客服"
    },

    ja: {
      "Logout":"ログアウト",
      "Users":"ユーザー",
      "Balances":"残高",
      "Deposits":"入金",
      "Withdrawals":"出金",
      "Support":"サポート",
      "Assets":"資産",
      "Available":"利用可能",
      "Frozen":"凍結",
      "Deposit":"入金",
      "Withdraw":"出金",
      "Transfer":"振替",
      "History":"履歴",
      "Home":"ホーム",
      "Markets":"マーケット",
      "Trade":"取引",
      "Language":"言語",
      "Username":"ユーザー名",
      "Password":"パスワード",
      "Register":"登録",
      "Sign In":"ログイン",
      "Create Account":"アカウント作成",
      "Forgot Password?":"パスワードをお忘れですか？",
      "Leverage":"レバレッジ",
      "Long":"ロング",
      "Short":"ショート",
      "Open Trade":"取引を開始",
      "Close Trade":"取引を決済",
      "Amount":"金額",
      "Profit / Loss":"損益",
      "All":"すべて",
      "Forex":"外国為替",
      "Crypto":"暗号資産",
      "Metals":"貴金属",
      "Indices":"指数",
      "Security":"セキュリティ",
      "Announcements":"お知らせ",
      "Latest Update":"最新更新",
      "My Orders":"注文履歴",
      "Subscribe":"購読",
      "Product":"商品",
      "Daily Income":"日次収益",
      "Duration":"期間",
      "Minimum":"最低額",
      "Confirm Withdrawal":"出金を確認",
      "Confirm Transfer":"振替を確認",
      "Contact Support":"サポートに連絡"
    },

    hi: {
      "Logout":"लॉग आउट",
      "Users":"उपयोगकर्ता",
      "Balances":"शेष राशि",
      "Deposits":"जमा",
      "Withdrawals":"निकासी",
      "Support":"सहायता",
      "Assets":"संपत्ति",
      "Available":"उपलब्ध",
      "Frozen":"फ्रोजन",
      "Deposit":"जमा करें",
      "Withdraw":"निकासी",
      "Transfer":"ट्रांसफर",
      "History":"इतिहास",
      "Home":"होम",
      "Markets":"मार्केट",
      "Trade":"ट्रेड",
      "Language":"भाषा",
      "Username":"उपयोगकर्ता नाम",
      "Password":"पासवर्ड",
      "Register":"रजिस्टर",
      "Sign In":"साइन इन",
      "Create Account":"खाता बनाएं",
      "Forgot Password?":"पासवर्ड भूल गए?",
      "Leverage":"लीवरेज",
      "Long":"लॉन्ग",
      "Short":"शॉर्ट",
      "Open Trade":"ट्रेड खोलें",
      "Close Trade":"ट्रेड बंद करें",
      "Amount":"राशि",
      "Profit / Loss":"लाभ / हानि",
      "All":"सभी",
      "Forex":"फॉरेक्स",
      "Crypto":"क्रिप्टो",
      "Metals":"मेटल",
      "Indices":"इंडेक्स",
      "Security":"सुरक्षा",
      "Announcements":"घोषणाएं",
      "Latest Update":"नवीनतम अपडेट",
      "My Orders":"मेरे ऑर्डर",
      "Subscribe":"सब्सक्राइब",
      "Product":"उत्पाद",
      "Daily Income":"दैनिक आय",
      "Duration":"अवधि",
      "Minimum":"न्यूनतम",
      "Confirm Withdrawal":"निकासी की पुष्टि करें",
      "Confirm Transfer":"ट्रांसफर की पुष्टि करें",
      "Contact Support":"सपोर्ट से संपर्क करें"
    },

    fr: {
      "Logout":"Se déconnecter",
      "Users":"Utilisateurs",
      "Balances":"Soldes",
      "Deposits":"Dépôts",
      "Withdrawals":"Retraits",
      "Support":"Support",
      "Assets":"Actifs",
      "Available":"Disponible",
      "Frozen":"Bloqué",
      "Deposit":"Dépôt",
      "Withdraw":"Retrait",
      "Transfer":"Transfert",
      "History":"Historique",
      "Home":"Accueil",
      "Markets":"Marchés",
      "Trade":"Trader",
      "Language":"Langue",
      "Username":"Nom d’utilisateur",
      "Password":"Mot de passe",
      "Register":"S’inscrire",
      "Sign In":"Se connecter",
      "Create Account":"Créer un compte",
      "Forgot Password?":"Mot de passe oublié ?",
      "Leverage":"Effet de levier",
      "Long":"Long",
      "Short":"Short",
      "Open Trade":"Ouvrir une position",
      "Close Trade":"Fermer la position",
      "Amount":"Montant",
      "Profit / Loss":"Profit / Perte",
      "All":"Tous",
      "Forex":"Forex",
      "Crypto":"Crypto",
      "Metals":"Métaux",
      "Indices":"Indices",
      "Security":"Sécurité",
      "Announcements":"Annonces",
      "Latest Update":"Dernière mise à jour",
      "My Orders":"Mes ordres",
      "Subscribe":"S’abonner",
      "Product":"Produit",
      "Daily Income":"Revenu quotidien",
      "Duration":"Durée",
      "Minimum":"Minimum",
      "Confirm Withdrawal":"Confirmer le retrait",
      "Confirm Transfer":"Confirmer le transfert",
      "Contact Support":"Contacter le support"
    },

    ur: {
      "Logout":"لاگ آؤٹ",
      "Users":"صارفین",
      "Balances":"بیلنس",
      "Deposits":"جمع",
      "Withdrawals":"رقم نکلوانا",
      "Support":"سپورٹ",
      "Assets":"اثاثے",
      "Available":"دستیاب",
      "Frozen":"منجمد",
      "Deposit":"جمع کروائیں",
      "Withdraw":"رقم نکلوائیں",
      "Transfer":"منتقلی",
      "History":"تاریخ",
      "Home":"ہوم",
      "Markets":"مارکیٹس",
      "Trade":"ٹریڈ",
      "Language":"زبان",
      "Username":"صارف نام",
      "Password":"پاس ورڈ",
      "Register":"رجسٹر",
      "Sign In":"سائن اِن",
      "Create Account":"اکاؤنٹ بنائیں",
      "Forgot Password?":"پاس ورڈ بھول گئے؟",
      "Leverage":"لیوریج",
      "Long":"لانگ",
      "Short":"شارٹ",
      "Open Trade":"ٹریڈ کھولیں",
      "Close Trade":"ٹریڈ بند کریں",
      "Amount":"رقم",
      "Profit / Loss":"منافع / نقصان",
      "All":"تمام",
      "Forex":"فاریکس",
      "Crypto":"کرپٹو",
      "Metals":"میٹلز",
      "Indices":"انڈیکس",
      "Security":"سیکیورٹی",
      "Announcements":"اعلانات",
      "Latest Update":"تازہ ترین اپ ڈیٹ",
      "My Orders":"میرے آرڈرز",
      "Subscribe":"سبسکرائب",
      "Product":"پروڈکٹ",
      "Daily Income":"روزانہ آمدنی",
      "Duration":"مدت",
      "Minimum":"کم از کم",
      "Confirm Withdrawal":"رقم نکلوانے کی تصدیق",
      "Confirm Transfer":"منتقلی کی تصدیق",
      "Contact Support":"سپورٹ سے رابطہ"
    }
  }
};
